# Ground truth samples for grader creation process completion

[samples.happy-path-complete]
score = 3

[[samples.happy-path-complete.messages]]
role = "user"
content = "hi"

[[samples.happy-path-complete.messages]]
role = "assistant"
content = "hello world"

[samples.wrong-greeting-failure]
score = -3

[[samples.wrong-greeting-failure.messages]]
role = "user"
content = "hi"

[[samples.wrong-greeting-failure.messages]]
role = "assistant"
content = "I like to move it move it"

[samples.partial-response-failure]
score = -3

[[samples.partial-response-failure.messages]]
role = "user"
content = "hi"

[[samples.partial-response-failure.messages]]
role = "assistant"
content = "World"

[samples.incomplete-greeting-failure]
score = -3

[[samples.incomplete-greeting-failure.messages]]
role = "user"
content = "hi"

[[samples.incomplete-greeting-failure.messages]]
role = "assistant"
content = "Hello"

[samples.case-mismatch-failure]
score = -3

[[samples.case-mismatch-failure.messages]]
role = "user"
content = "hi"

[[samples.case-mismatch-failure.messages]]
role = "assistant"
content = "Hello World"
