// @generated by infra/appBuild/routesBuild.ts
import { iso } from "apps/boltFoundry/__generated__/__isograph/iso.ts";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Query.EntrypointFormatter`)
iso(`entrypoint Query.EntrypointHome`)
iso(`entrypoint Query.EntrypointLogin`)

import entrypointFormatter from "apps/boltFoundry/__generated__/__isograph/Query/EntrypointFormatter/entrypoint.ts"
import entrypointHome from "apps/boltFoundry/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts"
import entrypointLogin from "apps/boltFoundry/__generated__/__isograph/Query/EntrypointLogin/entrypoint.ts"

export {entrypointFormatter};
export {entrypointHome};
export {entrypointLogin};
