// @generated by infra/appBuild/routesBuild.ts
import { iso } from "apps/boltFoundry/__generated__/__isograph/iso.ts";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Mutation.JoinWaitlist`)
iso(`entrypoint Query.EntrypointHome`)

import entrypointHome from "apps/boltFoundry/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts"
import joinWaitlist from "apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/entrypoint.ts"

export {entrypointHome};
export {joinWaitlist};
