// This file is auto-generated by contentBuild.ts
// DO NOT EDIT MANUALLY

import type { ComponentType } from "react";

// Map of available slugs for runtime checking
export const availableDocs = new Set([
  "code-example",
] as const);

// Derive the type from the Set values
export type DocSlug = typeof availableDocs extends Set<infer T> ? T : never;

// Type-safe helper to check if a slug is valid
export function isValidDocSlug(slug: string): slug is DocSlug {
  return availableDocs.has(slug as DocSlug);
}

// Lazy loader for documentation components
export async function loadDocComponent(slug: string): Promise<ComponentType | null> {
  if (!isValidDocSlug(slug)) {
    return null;
  }
  
  try {
    const module = await import(`build/docs/${slug}.js`);
    return module.default || null;
  } catch (error) {
    console.error(`Failed to load doc component ${slug}:`, error);
    return null;
  }
}
