// This file is auto-generated by contentBuild.ts
// DO NOT EDIT MANUALLY

import wut from "build/docs/wut.js";
import README from "build/docs/README.js";
import product_plan from "build/docs/product-plan.js";
import measurement_strategy from "build/docs/measurement-strategy.js";
import team_story from "build/docs/team-story.js";
import business_vision from "build/docs/business-vision.js";
import company_vision from "build/docs/company-vision.js";
import STATUS from "build/docs/STATUS.js";
import BACKLOG from "build/docs/BACKLOG.js";
import CHANGELOG from "build/docs/CHANGELOG.js";
import card_system from "build/docs/card-system.js";
import improving_inference_philosophy from "build/docs/improving-inference-philosophy.js";
import quickstart from "build/docs/quickstart.js";
import getting_started from "build/docs/getting-started.js";
import interactive_demo from "build/docs/interactive-demo.js";

export const docComponents = {
  "wut": wut,
  "README": README,
  "product-plan": product_plan,
  "measurement-strategy": measurement_strategy,
  "team-story": team_story,
  "business-vision": business_vision,
  "company-vision": company_vision,
  "STATUS": STATUS,
  "BACKLOG": BACKLOG,
  "CHANGELOG": CHANGELOG,
  "card-system": card_system,
  "improving-inference-philosophy": improving_inference_philosophy,
  "quickstart": quickstart,
  "getting-started": getting_started,
  "interactive-demo": interactive_demo,
} as const;

export type DocSlug = keyof typeof docComponents;
