export const easyQuestions = [
  {
    "category": "Mythology",
    "correct_answer": "Zeus",
    "difficulty": "easy",
    "id": "eeb8f3eae42344b788badcb36cae3ae8",
    "incorrect_answers": ["Apollo", "Hermes", "Poseidon"],
    "question": "Who was the King of Gods in Ancient Greek mythology?",
    "type": "multiple",
  },
  {
    "category": "Mythology",
    "correct_answer": "Thor",
    "difficulty": "easy",
    "id": "2a5fdee4221b4f9e9df733b5a8d8e68b",
    "incorrect_answers": ["Loki", "Odin", "Frey"],
    "question": "Who is the Norse god of thunder?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "George Washington",
    "difficulty": "easy",
    "id": "f345c5642e8a41269d879632e3a0aabc",
    "incorrect_answers": ["Thomas Jefferson", "Abraham Lincoln", "John Adams"],
    "question": "Who was the first president of the United States?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Water",
    "difficulty": "easy",
    "id": "b3c67e8fbe9b489b91045e1cc34c1d23",
    "incorrect_answers": ["Oxygen", "Hydrogen", "Carbon Dioxide"],
    "question": "What is the chemical substance H2O commonly known as?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Mount Everest",
    "difficulty": "easy",
    "id": "c8d123a097ae48e7ad9715c9d9fe2a1b",
    "incorrect_answers": ["K2", "Kilimanjaro", "Denali"],
    "question": "What is the tallest mountain in the world?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "William Shakespeare",
    "difficulty": "easy",
    "id": "e5b6b4a2794b4a019d7426b5cf542b8f",
    "incorrect_answers": ["Charles Dickens", "J.K. Rowling", "Mark Twain"],
    "question": "Who wrote 'Romeo and Juliet'?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Soccer",
    "difficulty": "easy",
    "id": "8d3457d1d5b44ad787abf0c8dfab6df1",
    "incorrect_answers": ["Basketball", "Tennis", "Baseball"],
    "question": "Which sport is known as football in most countries?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "The Beatles",
    "difficulty": "easy",
    "id": "bd673e9f9f9d4b8b9f2b54f3b9e0c986",
    "incorrect_answers": ["The Rolling Stones", "Led Zeppelin", "Pink Floyd"],
    "question": "Which band recorded the album 'Abbey Road'?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "Avatar",
    "difficulty": "easy",
    "id": "c7f1f53b29754a1391f8b3e1b9ae8e8f",
    "incorrect_answers": ["Titanic", "The Avengers", "Jurassic Park"],
    "question": "What is the highest-grossing movie of all time as of 2020?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Apple",
    "difficulty": "easy",
    "id": "24c58dcd474a4c9f8b9dc5a5c3b5d4d2",
    "incorrect_answers": ["Microsoft", "Google", "Samsung"],
    "question": "Which company created the iPhone?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "The Titanic",
    "difficulty": "easy",
    "id": "b8e5e2c8a9b64e96b89167c1b1f2dc1c",
    "incorrect_answers": ["Lusitania", "Queen Mary", "Britannic"],
    "question":
      "What was the name of the famous ship that sank in 1912 after hitting an iceberg?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Jupiter",
    "difficulty": "easy",
    "id": "9f4c22b4ef9b49828b1c64789c25ec1b",
    "incorrect_answers": ["Mars", "Saturn", "Earth"],
    "question": "Which is the largest planet in our solar system?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Pacific",
    "difficulty": "easy",
    "id": "f29f01a76ae9473485dc64a5caa2f89f",
    "incorrect_answers": ["Atlantic", "Indian", "Arctic"],
    "question": "Which is the largest ocean on Earth?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "Michael Jackson",
    "difficulty": "easy",
    "id": "53e25f2cbb7649f9989dbf7abdc12a91",
    "incorrect_answers": ["Prince", "Elvis Presley", "Freddie Mercury"],
    "question": "Who is known as the 'King of Pop'?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "Star Wars",
    "difficulty": "easy",
    "id": "4cd89f7c82324a2f8f2ac134d1a3e3f1",
    "incorrect_answers": ["Star Trek", "Guardians of the Galaxy", "Avatar"],
    "question":
      "Which movie franchise features the characters Luke Skywalker and Darth Vader?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Elon Musk",
    "difficulty": "easy",
    "id": "b2349d8fbac746129b5126c4a4d2a0f7",
    "incorrect_answers": ["Jeff Bezos", "Bill Gates", "Mark Zuckerberg"],
    "question": "Who is the CEO of SpaceX and Tesla?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "World War II",
    "difficulty": "easy",
    "id": "9f78b5d5c4b24102a8c9ef77d9f8d0d4",
    "incorrect_answers": ["World War I", "Vietnam War", "Korean War"],
    "question": "Which war was fought from 1939 to 1945?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Oxygen",
    "difficulty": "easy",
    "id": "ebf44f5c98bf4118b1e2f78cf2a59e68",
    "incorrect_answers": ["Hydrogen", "Nitrogen", "Carbon Dioxide"],
    "question": "What element do humans need to breathe?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Australia",
    "difficulty": "easy",
    "id": "a1e9b94a3c15438d9f21f8e29c79b4e7",
    "incorrect_answers": ["New Zealand", "Canada", "South Africa"],
    "question": "Which country is both a continent and an island?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Michael Jordan",
    "difficulty": "easy",
    "id": "a28db3f782b941a88b2f63f6e489012f",
    "incorrect_answers": ["LeBron James", "Kobe Bryant", "Shaquille O'Neal"],
    "question":
      "Which basketball player is often considered the greatest of all time and played for the Chicago Bulls?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "J.K. Rowling",
    "difficulty": "easy",
    "id": "cd3f4f1da45149cb84f44e7b52fdefe8",
    "incorrect_answers": ["George R.R. Martin", "Tolkien", "Suzanne Collins"],
    "question": "Who wrote the 'Harry Potter' series?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "Titanic",
    "difficulty": "easy",
    "id": "fad1f02e71254bb599c59e3a7c3d133d",
    "incorrect_answers": ["The Notebook", "Gone with the Wind", "Casablanca"],
    "question": "Which movie features the quote 'I'm the king of the world!'?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Google",
    "difficulty": "easy",
    "id": "ad93c6f3b0d94d1e81f1b8f6e7d0d3d9",
    "incorrect_answers": ["Yahoo", "Bing", "Amazon"],
    "question": "Which company developed the Android operating system?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Isaac Newton",
    "difficulty": "easy",
    "id": "8fb42ec7a30e4da6af3d9bb8f7b72f7c",
    "incorrect_answers": ["Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
    "question": "Who formulated the laws of motion and gravity?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Roger Federer",
    "difficulty": "easy",
    "id": "fa45a6b9eb1f409d97562b9ed0af1e8d",
    "incorrect_answers": ["Rafael Nadal", "Novak Djokovic", "Andy Murray"],
    "question":
      "Who has won the most men's singles Grand Slam titles in tennis?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "The Moon",
    "difficulty": "easy",
    "id": "d92f6bf5e9b74bbf8f48b5e6eb7f8b4b",
    "incorrect_answers": ["Mars", "Venus", "Jupiter"],
    "question":
      "Where did humans first land in 1969 during the Apollo 11 mission?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Africa",
    "difficulty": "easy",
    "id": "7d654ef43a6c478fae77d5a2f2a7c6f1",
    "incorrect_answers": ["Asia", "Europe", "South America"],
    "question": "Which continent is the Sahara Desert located on?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "Indiana Jones",
    "difficulty": "easy",
    "id": "c9b6a34b4b3b42b59f34f6b9e7e4f4a8",
    "incorrect_answers": ["James Bond", "Luke Skywalker", "Han Solo"],
    "question":
      "Which movie character is an archaeologist known for his adventures with a whip and fedora?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Amazon",
    "difficulty": "easy",
    "id": "8d4a93f87ba74b62a6543b5f3b9e9d0f",
    "incorrect_answers": ["eBay", "Alibaba", "Flipkart"],
    "question":
      "Which company was founded by Jeff Bezos and started as an online bookstore?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Pluto",
    "difficulty": "easy",
    "id": "d0b5e43f75b84304bde76b5e5b5b78a1",
    "incorrect_answers": ["Mars", "Neptune", "Uranus"],
    "question":
      "Which dwarf planet was once considered the ninth planet in the solar system?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "Nelson Mandela",
    "difficulty": "easy",
    "id": "f1b45e5a89d5446a85c2a67b69a7e5a1",
    "incorrect_answers": [
      "Mahatma Gandhi",
      "Martin Luther King Jr.",
      "Winston Churchill",
    ],
    "question": "Who was the first black president of South Africa?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Lionel Messi",
    "difficulty": "easy",
    "id": "fa78f5f7b8a747f79b74c8f5b4f6a7e8",
    "incorrect_answers": ["Cristiano Ronaldo", "Neymar", "Kylian Mbappe"],
    "question":
      "Which football player has won multiple Ballon d'Or awards and played for Barcelona?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Nile",
    "difficulty": "easy",
    "id": "c8f7a4e9f7c34b1a8d7f9b8b5e9f7c8b",
    "incorrect_answers": ["Amazon", "Yangtze", "Mississippi"],
    "question": "Which is the longest river in the world?",
    "type": "multiple",
  },
];
