export const mediumQuestions = [
  {
    "category": "Mythology",
    "correct_answer": "Ares",
    "difficulty": "medium",
    "id": "aa23432f93c7480fbc813eaf53e1eabc",
    "incorrect_answers": ["Apollo", "Hermes", "Hephaestus"],
    "question": "Which Greek god was known as the god of war?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "Genghis Khan",
    "difficulty": "medium",
    "id": "bfb234ae892f4a9fbb234b3342a8ae8d",
    "incorrect_answers": [
      "Attila the Hun",
      "Alexander the Great",
      "Julius Caesar",
    ],
    "question": "Who founded the Mongol Empire?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "DNA",
    "difficulty": "medium",
    "id": "bc834f98b22a41fbbd845f6fcb9f432e",
    "incorrect_answers": ["RNA", "mRNA", "ATP"],
    "question":
      "What molecule carries the genetic instructions used in the growth and development of all living organisms?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Amazon",
    "difficulty": "medium",
    "id": "ca134fb893af48948ae0fbb8f2a4df5b",
    "incorrect_answers": ["Nile", "Yangtze", "Danube"],
    "question": "What is the largest river by discharge volume of water?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "Fyodor Dostoevsky",
    "difficulty": "medium",
    "id": "d56f44adf2234ba888fe5d0abf67896c",
    "incorrect_answers": ["Leo Tolstoy", "Anton Chekhov", "Nikolai Gogol"],
    "question": "Who wrote the novel 'Crime and Punishment'?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Roger Federer",
    "difficulty": "medium",
    "id": "ed2345ad9e4249bb92a4f8cf5c0d891b",
    "incorrect_answers": ["Rafael Nadal", "Andy Murray", "Novak Djokovic"],
    "question": "Which tennis player has the most Wimbledon titles?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "Led Zeppelin",
    "difficulty": "medium",
    "id": "f567dd3344a54b6c94bfe5cb673e4b9d",
    "incorrect_answers": ["Pink Floyd", "The Rolling Stones", "The Who"],
    "question":
      "Which band released the album 'Led Zeppelin IV' featuring the song 'Stairway to Heaven'?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "Christopher Nolan",
    "difficulty": "medium",
    "id": "d3f8769b7e8f45d7879e1d7a90e6d9d8",
    "incorrect_answers": [
      "Quentin Tarantino",
      "Steven Spielberg",
      "James Cameron",
    ],
    "question": "Who directed the film 'Inception'?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Alan Turing",
    "difficulty": "medium",
    "id": "ef7e2dcb8bb14b14b2f8774a0d243f0a",
    "incorrect_answers": ["Bill Gates", "Charles Babbage", "Steve Jobs"],
    "question":
      "Who is considered the father of computer science and artificial intelligence?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "The Battle of Hastings",
    "difficulty": "medium",
    "id": "c8d91a9f1a6b4b6e8e1a5a892ce9b4ae",
    "incorrect_answers": [
      "Battle of Agincourt",
      "Battle of Waterloo",
      "Battle of Trafalgar",
    ],
    "question": "What battle in 1066 led to the Norman conquest of England?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Einstein",
    "difficulty": "medium",
    "id": "b55f5a53fdfa4d04b098ed5d567c013c",
    "incorrect_answers": ["Newton", "Galileo", "Bohr"],
    "question": "Who formulated the theory of relativity?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Australia",
    "difficulty": "medium",
    "id": "d63e789a6ba5474abfe88b6d68933c1b",
    "incorrect_answers": ["Canada", "India", "South Africa"],
    "question": "Which country has the largest coral reef system in the world?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "Homer",
    "difficulty": "medium",
    "id": "b55623f3e4d14b8db9881f03452345ad",
    "incorrect_answers": ["Virgil", "Ovid", "Sophocles"],
    "question": "Who is the author of 'The Iliad' and 'The Odyssey'?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "New York Yankees",
    "difficulty": "medium",
    "id": "e0f6b10a59db409f99c9b9ac5cf9d4d7",
    "incorrect_answers": [
      "Los Angeles Dodgers",
      "Boston Red Sox",
      "Chicago Cubs",
    ],
    "question": "Which baseball team has won the most World Series titles?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "Beyoncé",
    "difficulty": "medium",
    "id": "f456fbb2abfd4f67b2f7f7a98a9b5d7a",
    "incorrect_answers": ["Rihanna", "Adele", "Taylor Swift"],
    "question":
      "Which artist is known for the album 'Lemonade' and was a former member of Destiny's Child?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "The Matrix",
    "difficulty": "medium",
    "id": "adff44ae23f34b4c89a4b6ae56f9b5b8",
    "incorrect_answers": ["Blade Runner", "Inception", "Terminator"],
    "question": "Which movie features the line 'There is no spoon'?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Steve Jobs",
    "difficulty": "medium",
    "id": "dbf44ef12b3649bfa012f4a56df8bb9c",
    "incorrect_answers": ["Bill Gates", "Larry Page", "Sergey Brin"],
    "question": "Who was the co-founder of Apple Inc.?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "Napoleon Bonaparte",
    "difficulty": "medium",
    "id": "ef7d23cfe787490b8877df32d9e8782d",
    "incorrect_answers": [
      "Julius Caesar",
      "Alexander the Great",
      "Charlemagne",
    ],
    "question": "Who crowned himself Emperor of France in 1804?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Mercury",
    "difficulty": "medium",
    "id": "e9f88b59e8724f9287c9e5e8c9c9e3a7",
    "incorrect_answers": ["Venus", "Mars", "Earth"],
    "question": "Which planet is closest to the Sun?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Machu Picchu",
    "difficulty": "medium",
    "id": "a78e9d3ad8e4487f92c2b1cbacbf5a9d",
    "incorrect_answers": ["Tikal", "Chichen Itza", "Petra"],
    "question": "Which ancient city is located in the Andes Mountains of Peru?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "George Orwell",
    "difficulty": "medium",
    "id": "abf99a77f12c4bb7b789b7c23a25efb9",
    "incorrect_answers": ["Aldous Huxley", "Ray Bradbury", "J.R.R. Tolkien"],
    "question": "Who wrote the novel '1984'?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "Brazil",
    "difficulty": "medium",
    "id": "f9adf23e79f74ae1b9c7e9cb9d8f8d1a",
    "incorrect_answers": ["Germany", "Argentina", "Italy"],
    "question": "Which country has won the most FIFA World Cup titles?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "The Beatles",
    "difficulty": "medium",
    "id": "fe9ad44fbb964bcb9f7f9c8e4d0a5b2b",
    "incorrect_answers": ["The Rolling Stones", "The Who", "Pink Floyd"],
    "question":
      "Which band released the album 'Sgt. Pepper's Lonely Hearts Club Band'?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "The Godfather",
    "difficulty": "medium",
    "id": "cfadf44be4c7482db8f8d9e8b7e9d8c7",
    "incorrect_answers": ["Goodfellas", "Scarface", "Casino"],
    "question":
      "Which movie features the quote 'I'm gonna make him an offer he can't refuse'?",
    "type": "multiple",
  },
  {
    "category": "Technology",
    "correct_answer": "Linux",
    "difficulty": "medium",
    "id": "bc8af7e23f3d4ae498df9b87b9d7c8f7",
    "incorrect_answers": ["Windows", "MacOS", "Unix"],
    "question":
      "Which open-source operating system was created by Linus Torvalds?",
    "type": "multiple",
  },
  {
    "category": "History",
    "correct_answer": "Berlin Wall",
    "difficulty": "medium",
    "id": "ba8aef90dd93489a9b7c9a5f8e9c7d6b",
    "incorrect_answers": [
      "Great Wall of China",
      "Iron Curtain",
      "Maginot Line",
    ],
    "question":
      "Which wall separated East and West Berlin during the Cold War?",
    "type": "multiple",
  },
  {
    "category": "Science",
    "correct_answer": "Higgs boson",
    "difficulty": "medium",
    "id": "dfb8e2adf5b9438b9f7e9b8e9b4f7a8f",
    "incorrect_answers": ["Neutrino", "Photon", "Quark"],
    "question":
      "What subatomic particle is often referred to as the 'God particle'?",
    "type": "multiple",
  },
  {
    "category": "Geography",
    "correct_answer": "Mount Kilimanjaro",
    "difficulty": "medium",
    "id": "e5b9c3a7f3e84dfcb9d9e5f7e4b8f7d9",
    "incorrect_answers": ["Mount Everest", "Mount Elbrus", "Mount Denali"],
    "question": "What is the highest mountain in Africa?",
    "type": "multiple",
  },
  {
    "category": "Literature",
    "correct_answer": "Mary Shelley",
    "difficulty": "medium",
    "id": "fa9df5ae90d74a89b8f7e3b3c9d9d7e5",
    "incorrect_answers": ["Bram Stoker", "Edgar Allan Poe", "H.G. Wells"],
    "question": "Who wrote the novel 'Frankenstein'?",
    "type": "multiple",
  },
  {
    "category": "Sports",
    "correct_answer": "LeBron James",
    "difficulty": "medium",
    "id": "bb4fd7c5a7c84d7a9c9e9c7b3e7f9d3a",
    "incorrect_answers": ["Michael Jordan", "Kobe Bryant", "Shaquille O'Neal"],
    "question":
      "Which NBA player is known as 'King James' and played for the Cleveland Cavaliers, Miami Heat, and Los Angeles Lakers?",
    "type": "multiple",
  },
  {
    "category": "Music",
    "correct_answer": "Elvis Presley",
    "difficulty": "medium",
    "id": "fa3bc4a78b0d479b8c8b9c7d5d9b8f7e",
    "incorrect_answers": ["Johnny Cash", "Buddy Holly", "Jerry Lee Lewis"],
    "question": "Who is known as the 'King of Rock and Roll'?",
    "type": "multiple",
  },
  {
    "category": "Movies",
    "correct_answer": "The Dark Knight",
    "difficulty": "medium",
    "id": "ef7d2b3a9b9d44b4a6c9e7f9d7a8d3e5",
    "incorrect_answers": ["Batman Begins", "Joker", "Man of Steel"],
    "question":
      "Which 2008 film stars Christian Bale as Batman and Heath Ledger as the Joker?",
    "type": "multiple",
  },
];
