// @generated by infra/appBuild/routesBuild.ts
import { iso } from "@iso-bfc";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
  status?: number;
  headers?: Record<string, string>;
};

iso(`entrypoint Mutation.JoinWaitlist`)
iso(`entrypoint Query.EntrypointBlog`)
iso(`entrypoint Query.EntrypointEval`)
iso(`entrypoint Query.EntrypointHome`)
iso(`entrypoint Query.EntrypointLogin`)
iso(`entrypoint Query.EntrypointRlhf`)

import entrypointBlog from "@iso-bfc/Query/EntrypointBlog/entrypoint.ts"
import entrypointEval from "@iso-bfc/Query/EntrypointEval/entrypoint.ts"
import entrypointHome from "@iso-bfc/Query/EntrypointHome/entrypoint.ts"
import entrypointLogin from "@iso-bfc/Query/EntrypointLogin/entrypoint.ts"
import entrypointRlhf from "@iso-bfc/Query/EntrypointRlhf/entrypoint.ts"
import joinWaitlist from "@iso-bfc/Mutation/JoinWaitlist/entrypoint.ts"

export {entrypointBlog};
export {entrypointEval};
export {entrypointHome};
export {entrypointLogin};
export {entrypointRlhf};
export {joinWaitlist};
