// @generated by infra/appBuild/routesBuild.ts
import { iso } from "@iso-bfc";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Query.EntrypointHome`)
iso(`entrypoint Query.EntrypointRlhf`)

import entrypointHome from "@iso-bfc/Query/EntrypointHome/entrypoint.ts"
import entrypointRlhf from "@iso-bfc/Query/EntrypointRlhf/entrypoint.ts"

export {entrypointHome};
export {entrypointRlhf};
