// @generated by infra/appBuild/routesBuild.ts
import { iso } from "@iso-bfc";

export type RouteEntrypoint = {
  Body: React.FC | null | undefined;
  title: string;
};

iso(`entrypoint Query.EntrypointHome`)

import entrypointHome from "@iso-bfc/Query/EntrypointHome/entrypoint.ts"

export {entrypointHome};
