export const fakeClips = [
  {
    id: "a1b2c3",
    title: "Reflecting on being from Idaho",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old1",
  },
  {
    id: "d4e5f6",
    title: "Exploring the mountains of Colorado",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old2",
  },
  {
    id: "g7h8i9",
    title: "Learning to surf in California",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old3",
  },
  {
    id: "j1k2l3",
    title: "A day in the life of a New Yorker",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old4",
  },
  {
    id: "m4n5o6",
    title: "Experiencing the hustle of Tokyo",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old5",
  },
  {
    id: "p7q8r9",
    title: "Street food adventures in Thailand",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old6",
  },
  {
    id: "s1t2u3",
    title: "Discovering the pyramids of Egypt",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old7",
  },
  {
    id: "v4w5x6",
    title: "A culinary journey through Italy",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old8",
  },
  {
    id: "y7z8a1",
    title: "Wildlife safari in Kenya",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old9",
  },
  {
    id: "b2c3d4",
    title: "Navigating the canals of Venice",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old10",
  },
  {
    id: "e5f6g7",
    title: "Finding peace in the Tibetan monasteries",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old11",
  },
  {
    id: "h8i9j1",
    title: "Scuba diving in the Great Barrier Reef",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old12",
  },
  {
    id: "k2l3m4",
    title: "Exploring the fjords of Norway",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old13",
  },
  {
    id: "n5o6p7",
    title: "A Journey into Coding",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old14",
  },
  {
    id: "q8r9s1",
    title: "The Beauty of Nature",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old15",
  },
  {
    id: "t2u3v4",
    title: "Historic Sites of Europe",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old16",
  },
  {
    id: "w5x6y7",
    title: "Adventures in Space",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old17",
  },
  {
    id: "z8a1b2",
    title: "Adventures in the Amazon",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old18",
  },
  {
    id: "c3d4e5",
    title: "Tranquil Beaches of Bali",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old19",
  },
  {
    id: "f6g7h8",
    title: "Cultural Festivities of India",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old20",
  },
  {
    id: "i9j1k2",
    title: "Skiing in the Alps",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old21",
  },

  {
    id: "l3m4n5",
    title: "Challenges of Arctic Exploration",
    owner: "george",
    client: "Comedy Shows Near Me",
    oldClipId: "old22",
  },
  {
    id: "o6p7q8",
    title: "Hidden Treasures of the Sahara",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old23",
  },
  {
    id: "r9s1t2",
    title: "Diving into Deep Learning",
    owner: "george",
    client: "Shock Collar",
    oldClipId: "old24",
  },
  {
    id: "u3v4w5",
    title: "Secrets of the Rainforest",
    owner: "mofe",
    client: "Tiny Cupboard",
    oldClipId: "old25",
  },
];
export const fakeClipReviews = [
  {
    id: "review14",
    clipId: "n5o6p7",
    oldClipId: "old14",
  },
  {
    id: "review15",
    clipId: "q8r9s1",
    oldClipId: "old15",
  },
  {
    id: "review16",
    clipId: "t2u3v4",
    oldClipId: "old16",
  },
  {
    id: "review17",
    clipId: "w5x6y7",
    oldClipId: "old17",
  },
  {
    id: "review18",
    clipId: "z8a1b2",
    oldClipId: "old18",
  },
  {
    id: "review19",
    clipId: "c3d4e5",
    oldClipId: "old19",
  },
  {
    id: "review20",
    clipId: "f6g7h8",
    oldClipId: "old20",
  },
  {
    id: "review21",
    clipId: "i9j1k2",
    oldClipId: "old21",
  },
  {
    id: "review22",
    clipId: "l3m4n5",
    oldClipId: "old22",
  },
  {
    id: "review23",
    clipId: "o6p7q8",
    oldClipId: "old23",
  },
  {
    id: "review24",
    clipId: "r9s1t2",
    oldClipId: "old24",
  },
  {
    id: "review25",
    clipId: "u3v4w5",
    oldClipId: "old25",
  },
];
export const fakeReviewComments = [
  {
    id: "review14Comment1",
    reviewId: "review14",
    timecode: 5,
    text: "Fix syntax error",
  },
  {
    id: "review14Comment2",
    reviewId: "review14",
    timecode: 10,
    text: "Update variable names for clarity",
  },
  {
    id: "review14Comment3",
    reviewId: "review14",
    timecode: 15,
    text: "Refactor function to improve performance",
  },
  {
    id: "review14Comment4",
    reviewId: "review14",
    timecode: 20,
    text: "Add error handling for edge cases",
  },
  {
    id: "review14Comment5",
    reviewId: "review14",
    timecode: 25,
    text: "Update documentation for new features",
  },
  {
    id: "review15Comment1",
    reviewId: "review15",
    timecode: 3,
    text: "Improve image resolution",
  },
  {
    id: "review15Comment1",
    reviewId: "review15",
    timecode: 7,
    text: "Increase video brightness",
  },
  {
    id: "review15Comment1",
    reviewId: "review15",
    timecode: 9,
    text: "Correct typo in subtitle",
  },
  {
    id: "review16Comment1",
    reviewId: "review16",
    timecode: 4,
    text: "Correct historical dates",
  },
  {
    id: "review16Comment2",
    reviewId: "review16",
    timecode: 8,
    text: "Verify architectural accuracy",
  },
  {
    id: "review16Comment3",
    reviewId: "review16",
    timecode: 13,
    text: "Adjust lighting levels",
  },
  {
    id: "review16Comment4",
    reviewId: "review16",
    timecode: 21,
    text: "Add background music",
  },
  {
    id: "review17Comment1",
    reviewId: "review17",
    timecode: 12,
    text: "Update scientific data",
  },
  {
    id: "review17Comment2",
    reviewId: "review17",
    timecode: 18,
    text: "Correct trajectory formulas",
  },
  {
    id: "review17Comment3",
    reviewId: "review17",
    timecode: 24,
    text: "Add missing audio commentary",
  },
  {
    id: "review17Comment4",
    reviewId: "review17",
    timecode: 30,
    text: "Adjust color balance",
  },
  {
    id: "review17Comment5",
    reviewId: "review17",
    timecode: 35,
    text: "Update mission timeline",
  },
  {
    id: "review17Comment6",
    reviewId: "review17",
    timecode: 42,
    text: "Improve graphical overlays",
  },
  {
    id: "review17Comment7",
    reviewId: "review17",
    timecode: 50,
    text: "Verify astronaut bios",
  },
  {
    id: "review17Comment8",
    reviewId: "review17",
    timecode: 55,
    text: "Update space station specs",
  },
  {
    id: "review17Comment9",
    reviewId: "review17",
    timecode: 60,
    text: "Enhance star maps accuracy",
  },
  {
    id: "review17Comment10",
    reviewId: "review17",
    timecode: 65,
    text: "Revise orbital data",
  },
  {
    id: "review17Comment11",
    reviewId: "review17",
    timecode: 70,
    text: "Correct planetary distances",
  },
  {
    id: "review17Comment12",
    reviewId: "review17",
    timecode: 75,
    text: "Review spacewalk procedures",
  },
  {
    id: "review24Comment1",
    reviewId: "review24",
    timecode: 2,
    text: "Improve model accuracy",
  },
  {
    id: "review24Comment2",
    reviewId: "review24",
    timecode: 14,
    text: "Optimize data preprocessing",
  },
  {
    id: "review24Comment3",
    reviewId: "review24",
    timecode: 27,
    text: "Refine hyperparameters",
  },
];
export const fakeReviewDecisions = [
  {
    id: "decision14",
    reviewId: "review14",
    decision: "changes",
  },
  {
    id: "decision15",
    reviewId: "review15",
    decision: "changes",
  },
  {
    id: "decision16",
    reviewId: "review16",
    decision: "changes",
  },
  {
    id: "decision17",
    reviewId: "review17",
    decision: "changes",
  },
  {
    id: "decision18",
    reviewId: "review18",
    decision: "approved",
  },
  {
    id: "decision19",
    reviewId: "review19",
    decision: "approved",
  },
  {
    id: "decision20",
    reviewId: "review20",
    decision: "approved",
  },
  {
    id: "decision21",
    reviewId: "review21",
    decision: "approved",
  },
  {
    id: "decision22",
    reviewId: "review22",
    decision: "rejected",
  },
  {
    id: "decision23",
    reviewId: "review23",
    decision: "rejected",
  },
  {
    id: "decision24",
    reviewId: "review24",
    decision: "changes",
  },
  {
    id: "decision25",
    reviewId: "review25",
    decision: "rejected",
  },
];
