/* @generated */
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "File";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Url";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "File";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Url";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SubmitContactFormInput: { // input type
    company?: string | null; // String
    email: string; // String!
    message: string; // String!
    name: string; // String!
    phone?: string | null; // String
  }
}

export interface NexusGenEnums {
  AccountRole: "ADMIN" | "ANON" | "MEMBER" | "OMNI" | "OWNER" | "REFRESH_CREDENTIALS_ONLY" | "SERVICE_INGESTION"
  PostStatus: "Dev only" | "Ready for publish"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  File: File
  Url: string
}

export interface NexusGenObjects {
  Annotations: { // root type
    bold?: boolean | null; // Boolean
    code?: boolean | null; // Boolean
    color?: string | null; // String
    italic?: boolean | null; // Boolean
    strikethrough?: boolean | null; // Boolean
    underlined?: boolean | null; // Boolean
  }
  AssemblyAIWord: { // root type
    confidence?: number | null; // Float
    end?: number | null; // Int
    speaker?: string | null; // String
    start?: number | null; // Int
    text?: string | null; // String
    word?: string | null; // String
  }
  BfAccount: { // root type
    displayName?: string | null; // String
    organizationBfGid?: string | null; // ID
    personBfGid?: string | null; // ID
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes?: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfClip: { // root type
    title?: string | null; // String
  }
  BfClipReview: { // root type
    mediaUrl?: NexusGenScalars['Url'] | null; // Url
    title?: string | null; // String
  }
  BfClipReviewConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfClipReviewEdge'] | null> | null; // [BfClipReviewEdge]
    nodes?: Array<NexusGenRootTypes['BfClipReview'] | null> | null; // [BfClipReview]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfClipReviewEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfClipReview'] | null; // BfClipReview
  }
  BfCurrentViewerAccessToken: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfCurrentViewerAnon: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfGoogleDriveResource: { // root type
    name?: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes?: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // root type
    fileId?: string | null; // String
    filename?: string | null; // String
  }
  BfMediaConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes?: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaNodeTranscript: { // root type
    filename?: string | null; // String
    words?: Array<NexusGenRootTypes['AssemblyAIWord'] | null> | null; // [AssemblyAIWord]
  }
  BfMediaNodeTranscriptConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaNodeTranscriptEdge'] | null> | null; // [BfMediaNodeTranscriptEdge]
    nodes?: Array<NexusGenRootTypes['BfMediaNodeTranscript'] | null> | null; // [BfMediaNodeTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaNodeTranscriptEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
  }
  BfOrganization: { // root type
    id: string; // ID!
    name?: string | null; // String
  }
  BfPerson: { // root type
    email?: string | null; // String
    name?: string | null; // String
  }
  BfSearchResult: { // root type
    creator?: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    query?: string | null; // String
  }
  BfSearchResultConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfSearchResultEdge'] | null> | null; // [BfSearchResultEdge]
    nodes?: Array<NexusGenRootTypes['BfSearchResult'] | null> | null; // [BfSearchResult]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSearchResultEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfSearchResult'] | null; // BfSearchResult
  }
  BfSearchResultItem: {};
  BfSearchResultItemConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfSearchResultItemEdge'] | null> | null; // [BfSearchResultItemEdge]
    nodes?: Array<NexusGenRootTypes['BfSearchResultItem'] | null> | null; // [BfSearchResultItem]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSearchResultItemEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfSearchResultItem'] | null; // BfSearchResultItem
  }
  Blog: { // root type
    title?: string | null; // String
  }
  BlogPost: { // root type
    coverUrl?: string | null; // String
    icon?: string | null; // String
    id: string; // String!
    slug?: string | null; // String
    status?: NexusGenEnums['PostStatus'] | null; // PostStatus
    summary?: string | null; // String
    title?: string | null; // String
  }
  BlogPostAuthor: { // root type
    avatarUrl?: string | null; // String
    email?: string | null; // String
    name?: string | null; // String
  }
  BlogPostConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes?: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  CalloutBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color?: string | null; // String
    icon?: string | null; // String
    id?: string | null; // String
    type?: string | null; // String
  }
  CodeBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id?: string | null; // String
    language?: string | null; // String
    type?: string | null; // String
  }
  DownloadMutationPayload: { // root type
    success: boolean; // Boolean!
  }
  ImageBlock: { // root type
    caption?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id?: string | null; // String
    imgUrl?: string | null; // String
    type?: string | null; // String
  }
  Link: { // root type
    url?: string | null; // String
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  ParagraphBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color?: string | null; // String
    id?: string | null; // String
    type?: string | null; // String
  }
  Query: {};
  RichText: { // root type
    annotations?: NexusGenRootTypes['Annotations'] | null; // Annotations
    text?: NexusGenRootTypes['Text'] | null; // Text
    type?: string | null; // String
  }
  SubmitContactFormPayload: { // root type
    message?: string | null; // String
    success: boolean; // Boolean!
  }
  Subscription: {};
  Text: { // root type
    content?: string | null; // String
    link?: NexusGenRootTypes['Link'] | null; // Link
  }
}

export interface NexusGenInterfaces {
  BfCurrentViewer: core.Discriminate<'BfCurrentViewerAccessToken', 'required'> | core.Discriminate<'BfCurrentViewerAnon', 'required'>;
  BfNode: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfClip', 'required'> | core.Discriminate<'BfClipReview', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaNodeTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'> | core.Discriminate<'BfSearchResult', 'required'> | core.Discriminate<'BfSearchResultItem', 'required'>;
  BlogPostContentBlock: core.Discriminate<'CalloutBlock', 'optional'> | core.Discriminate<'CodeBlock', 'optional'> | core.Discriminate<'ImageBlock', 'optional'> | core.Discriminate<'ParagraphBlock', 'optional'>;
  Node: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfClip', 'required'> | core.Discriminate<'BfClipReview', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaNodeTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'> | core.Discriminate<'BfSearchResult', 'required'> | core.Discriminate<'BfSearchResultItem', 'required'>;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Annotations: { // field return type
    bold: boolean | null; // Boolean
    code: boolean | null; // Boolean
    color: string | null; // String
    italic: boolean | null; // Boolean
    strikethrough: boolean | null; // Boolean
    underlined: boolean | null; // Boolean
  }
  AssemblyAIWord: { // field return type
    confidence: number | null; // Float
    end: number | null; // Int
    speaker: string | null; // String
    start: number | null; // Int
    text: string | null; // String
    word: string | null; // String
  }
  BfAccount: { // field return type
    displayName: string | null; // String
    id: string; // ID!
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    organizationBfGid: string | null; // ID
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    personBfGid: string | null; // ID
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfClip: { // field return type
    id: string; // ID!
    title: string | null; // String
  }
  BfClipReview: { // field return type
    id: string; // ID!
    mediaUrl: NexusGenScalars['Url'] | null; // Url
    title: string | null; // String
  }
  BfClipReviewConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfClipReviewEdge'] | null> | null; // [BfClipReviewEdge]
    nodes: Array<NexusGenRootTypes['BfClipReview'] | null> | null; // [BfClipReview]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfClipReviewEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfClipReview'] | null; // BfClipReview
  }
  BfCurrentViewerAccessToken: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
    searchResults: NexusGenRootTypes['BfSearchResultConnection'] | null; // BfSearchResultConnection
  }
  BfCurrentViewerAnon: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
    searchResults: NexusGenRootTypes['BfSearchResultConnection'] | null; // BfSearchResultConnection
  }
  BfGoogleDriveResource: { // field return type
    id: string; // ID!
    name: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // field return type
    fileId: string | null; // String
    filename: string | null; // String
    id: string; // ID!
    transcripts: NexusGenRootTypes['BfMediaNodeTranscriptConnection'] | null; // BfMediaNodeTranscriptConnection
  }
  BfMediaConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaNodeTranscript: { // field return type
    filename: string | null; // String
    id: string; // ID!
    words: Array<NexusGenRootTypes['AssemblyAIWord'] | null> | null; // [AssemblyAIWord]
  }
  BfMediaNodeTranscriptConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaNodeTranscriptEdge'] | null> | null; // [BfMediaNodeTranscriptEdge]
    nodes: Array<NexusGenRootTypes['BfMediaNodeTranscript'] | null> | null; // [BfMediaNodeTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaNodeTranscriptEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
  }
  BfOrganization: { // field return type
    googleDriveFolders: NexusGenRootTypes['BfGoogleDriveResourceConnection'] | null; // BfGoogleDriveResourceConnection
    id: string; // ID!
    media: NexusGenRootTypes['BfMediaConnection'] | null; // BfMediaConnection
    name: string | null; // String
    reviewableClips: NexusGenRootTypes['BfClipReviewConnection'] | null; // BfClipReviewConnection
  }
  BfPerson: { // field return type
    accounts: NexusGenRootTypes['BfAccountConnection'] | null; // BfAccountConnection
    email: string | null; // String
    googleAuthAccessToken: string | null; // String
    id: string; // ID!
    name: string | null; // String
  }
  BfSearchResult: { // field return type
    collectionLength: number | null; // Int
    creator: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    id: string; // ID!
    query: string | null; // String
    searchResultItems: NexusGenRootTypes['BfSearchResultItemConnection'] | null; // BfSearchResultItemConnection
    status: string | null; // String
  }
  BfSearchResultConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfSearchResultEdge'] | null> | null; // [BfSearchResultEdge]
    nodes: Array<NexusGenRootTypes['BfSearchResult'] | null> | null; // [BfSearchResult]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSearchResultEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfSearchResult'] | null; // BfSearchResult
  }
  BfSearchResultItem: { // field return type
    id: string; // ID!
  }
  BfSearchResultItemConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfSearchResultItemEdge'] | null> | null; // [BfSearchResultItemEdge]
    nodes: Array<NexusGenRootTypes['BfSearchResultItem'] | null> | null; // [BfSearchResultItem]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSearchResultItemEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfSearchResultItem'] | null; // BfSearchResultItem
  }
  Blog: { // field return type
    posts: NexusGenRootTypes['BlogPostConnection'] | null; // BlogPostConnection
    title: string | null; // String
  }
  BlogPost: { // field return type
    author: NexusGenRootTypes['BlogPostAuthor'] | null; // BlogPostAuthor
    content: Array<NexusGenRootTypes['BlogPostContentBlock'] | null> | null; // [BlogPostContentBlock]
    coverUrl: string | null; // String
    date: string | null; // String
    icon: string | null; // String
    id: string; // String!
    slug: string | null; // String
    status: NexusGenEnums['PostStatus'] | null; // PostStatus
    summary: string | null; // String
    title: string | null; // String
  }
  BlogPostAuthor: { // field return type
    avatarUrl: string | null; // String
    email: string | null; // String
    name: string | null; // String
  }
  BlogPostConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  CalloutBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color: string | null; // String
    icon: string | null; // String
    id: string | null; // String
    type: string | null; // String
  }
  CodeBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id: string | null; // String
    language: string | null; // String
    type: string | null; // String
  }
  DownloadMutationPayload: { // field return type
    success: boolean; // Boolean!
  }
  ImageBlock: { // field return type
    caption: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id: string | null; // String
    imgUrl: string | null; // String
    type: string | null; // String
  }
  Link: { // field return type
    url: string | null; // String
  }
  Mutation: { // field return type
    createSearchResult: NexusGenRootTypes['BfSearchResult'] | null; // BfSearchResult
    createTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
    deleteGoogleDriveResource: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
    deleteMedia: NexusGenRootTypes['BfMedia'] | null; // BfMedia
    deleteTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
    downloadClip: NexusGenRootTypes['DownloadMutationPayload'] | null; // DownloadMutationPayload
    linkAdvancedGoogleAuth: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    loginWithGoogle: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    logout: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    pickGoogleDriveFolder: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
    readTextFile: string | null; // String
    submitContactForm: NexusGenRootTypes['SubmitContactFormPayload'] | null; // SubmitContactFormPayload
    switchAccount: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    updateTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
    upsertClip: NexusGenRootTypes['BfClip'] | null; // BfClip
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  ParagraphBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color: string | null; // String
    id: string | null; // String
    type: string | null; // String
  }
  Query: { // field return type
    currentViewer: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  RichText: { // field return type
    annotations: NexusGenRootTypes['Annotations'] | null; // Annotations
    text: NexusGenRootTypes['Text'] | null; // Text
    type: string | null; // String
  }
  SubmitContactFormPayload: { // field return type
    message: string | null; // String
    success: boolean; // Boolean!
  }
  Subscription: { // field return type
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  Text: { // field return type
    content: string | null; // String
    link: NexusGenRootTypes['Link'] | null; // Link
  }
  BfCurrentViewer: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
    searchResults: NexusGenRootTypes['BfSearchResultConnection'] | null; // BfSearchResultConnection
  }
  BfNode: { // field return type
    id: string; // ID!
  }
  BlogPostContentBlock: { // field return type
    id: string | null; // String
    type: string | null; // String
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  Annotations: { // field return type name
    bold: 'Boolean'
    code: 'Boolean'
    color: 'String'
    italic: 'Boolean'
    strikethrough: 'Boolean'
    underlined: 'Boolean'
  }
  AssemblyAIWord: { // field return type name
    confidence: 'Float'
    end: 'Int'
    speaker: 'String'
    start: 'Int'
    text: 'String'
    word: 'String'
  }
  BfAccount: { // field return type name
    displayName: 'String'
    id: 'ID'
    organization: 'BfOrganization'
    organizationBfGid: 'ID'
    person: 'BfPerson'
    personBfGid: 'ID'
    role: 'AccountRole'
  }
  BfAccountConnection: { // field return type name
    count: 'Int'
    edges: 'BfAccountEdge'
    nodes: 'BfAccount'
    pageInfo: 'PageInfo'
  }
  BfAccountEdge: { // field return type name
    cursor: 'String'
    node: 'BfAccount'
  }
  BfClip: { // field return type name
    id: 'ID'
    title: 'String'
  }
  BfClipReview: { // field return type name
    id: 'ID'
    mediaUrl: 'Url'
    title: 'String'
  }
  BfClipReviewConnection: { // field return type name
    count: 'Int'
    edges: 'BfClipReviewEdge'
    nodes: 'BfClipReview'
    pageInfo: 'PageInfo'
  }
  BfClipReviewEdge: { // field return type name
    cursor: 'String'
    node: 'BfClipReview'
  }
  BfCurrentViewerAccessToken: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
    searchResults: 'BfSearchResultConnection'
  }
  BfCurrentViewerAnon: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
    searchResults: 'BfSearchResultConnection'
  }
  BfGoogleDriveResource: { // field return type name
    id: 'ID'
    name: 'String'
  }
  BfGoogleDriveResourceConnection: { // field return type name
    count: 'Int'
    edges: 'BfGoogleDriveResourceEdge'
    nodes: 'BfGoogleDriveResource'
    pageInfo: 'PageInfo'
  }
  BfGoogleDriveResourceEdge: { // field return type name
    cursor: 'String'
    node: 'BfGoogleDriveResource'
  }
  BfMedia: { // field return type name
    fileId: 'String'
    filename: 'String'
    id: 'ID'
    transcripts: 'BfMediaNodeTranscriptConnection'
  }
  BfMediaConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaEdge'
    nodes: 'BfMedia'
    pageInfo: 'PageInfo'
  }
  BfMediaEdge: { // field return type name
    cursor: 'String'
    node: 'BfMedia'
  }
  BfMediaNodeTranscript: { // field return type name
    filename: 'String'
    id: 'ID'
    words: 'AssemblyAIWord'
  }
  BfMediaNodeTranscriptConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaNodeTranscriptEdge'
    nodes: 'BfMediaNodeTranscript'
    pageInfo: 'PageInfo'
  }
  BfMediaNodeTranscriptEdge: { // field return type name
    cursor: 'String'
    node: 'BfMediaNodeTranscript'
  }
  BfOrganization: { // field return type name
    googleDriveFolders: 'BfGoogleDriveResourceConnection'
    id: 'ID'
    media: 'BfMediaConnection'
    name: 'String'
    reviewableClips: 'BfClipReviewConnection'
  }
  BfPerson: { // field return type name
    accounts: 'BfAccountConnection'
    email: 'String'
    googleAuthAccessToken: 'String'
    id: 'ID'
    name: 'String'
  }
  BfSearchResult: { // field return type name
    collectionLength: 'Int'
    creator: 'BfPerson'
    id: 'ID'
    query: 'String'
    searchResultItems: 'BfSearchResultItemConnection'
    status: 'String'
  }
  BfSearchResultConnection: { // field return type name
    count: 'Int'
    edges: 'BfSearchResultEdge'
    nodes: 'BfSearchResult'
    pageInfo: 'PageInfo'
  }
  BfSearchResultEdge: { // field return type name
    cursor: 'String'
    node: 'BfSearchResult'
  }
  BfSearchResultItem: { // field return type name
    id: 'ID'
  }
  BfSearchResultItemConnection: { // field return type name
    count: 'Int'
    edges: 'BfSearchResultItemEdge'
    nodes: 'BfSearchResultItem'
    pageInfo: 'PageInfo'
  }
  BfSearchResultItemEdge: { // field return type name
    cursor: 'String'
    node: 'BfSearchResultItem'
  }
  Blog: { // field return type name
    posts: 'BlogPostConnection'
    title: 'String'
  }
  BlogPost: { // field return type name
    author: 'BlogPostAuthor'
    content: 'BlogPostContentBlock'
    coverUrl: 'String'
    date: 'String'
    icon: 'String'
    id: 'String'
    slug: 'String'
    status: 'PostStatus'
    summary: 'String'
    title: 'String'
  }
  BlogPostAuthor: { // field return type name
    avatarUrl: 'String'
    email: 'String'
    name: 'String'
  }
  BlogPostConnection: { // field return type name
    count: 'Int'
    edges: 'BlogPostEdge'
    nodes: 'BlogPost'
    pageInfo: 'PageInfo'
  }
  BlogPostEdge: { // field return type name
    cursor: 'String'
    node: 'BlogPost'
  }
  CalloutBlock: { // field return type name
    RichText: 'RichText'
    color: 'String'
    icon: 'String'
    id: 'String'
    type: 'String'
  }
  CodeBlock: { // field return type name
    RichText: 'RichText'
    id: 'String'
    language: 'String'
    type: 'String'
  }
  DownloadMutationPayload: { // field return type name
    success: 'Boolean'
  }
  ImageBlock: { // field return type name
    caption: 'RichText'
    id: 'String'
    imgUrl: 'String'
    type: 'String'
  }
  Link: { // field return type name
    url: 'String'
  }
  Mutation: { // field return type name
    createSearchResult: 'BfSearchResult'
    createTranscript: 'BfMediaNodeTranscript'
    deleteGoogleDriveResource: 'BfGoogleDriveResource'
    deleteMedia: 'BfMedia'
    deleteTranscript: 'BfMediaNodeTranscript'
    downloadClip: 'DownloadMutationPayload'
    linkAdvancedGoogleAuth: 'BfCurrentViewer'
    loginWithGoogle: 'BfCurrentViewerAccessToken'
    logout: 'BfCurrentViewer'
    pickGoogleDriveFolder: 'BfGoogleDriveResource'
    readTextFile: 'String'
    submitContactForm: 'SubmitContactFormPayload'
    switchAccount: 'BfCurrentViewerAccessToken'
    updateTranscript: 'BfMediaNodeTranscript'
    upsertClip: 'BfClip'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  ParagraphBlock: { // field return type name
    RichText: 'RichText'
    color: 'String'
    id: 'String'
    type: 'String'
  }
  Query: { // field return type name
    currentViewer: 'BfCurrentViewer'
    node: 'BfNode'
  }
  RichText: { // field return type name
    annotations: 'Annotations'
    text: 'Text'
    type: 'String'
  }
  SubmitContactFormPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  Subscription: { // field return type name
    node: 'BfNode'
  }
  Text: { // field return type name
    content: 'String'
    link: 'Link'
  }
  BfCurrentViewer: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
    searchResults: 'BfSearchResultConnection'
  }
  BfNode: { // field return type name
    id: 'ID'
  }
  BlogPostContentBlock: { // field return type name
    id: 'String'
    type: 'String'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  BfCurrentViewerAccessToken: {
    searchResults: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfCurrentViewerAnon: {
    searchResults: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfMedia: {
    transcripts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfOrganization: {
    googleDriveFolders: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    media: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    reviewableClips: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfPerson: {
    accounts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfSearchResult: {
    searchResultItems: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Blog: {
    posts: { // args
      after?: string | null; // String
      author?: string | null; // String
      before?: string | null; // String
      date?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      slug?: string | null; // String
      status?: Array<NexusGenEnums['PostStatus'] | null> | null; // [PostStatus]
    }
  }
  Mutation: {
    createSearchResult: { // args
      query: string; // String!
    }
    createTranscript: { // args
      filename: string; // String!
      words: string; // String!
    }
    deleteGoogleDriveResource: { // args
      resourceId?: string | null; // String
    }
    deleteMedia: { // args
      id: string; // String!
    }
    deleteTranscript: { // args
      id: string; // String!
    }
    downloadClip: { // args
      endTime: number; // Float!
      mediaId: string; // String!
      startTime: number; // Float!
      title: string; // String!
      transcriptId: string; // String!
    }
    linkAdvancedGoogleAuth: { // args
      code: string; // String!
    }
    loginWithGoogle: { // args
      credential: string; // String!
    }
    pickGoogleDriveFolder: { // args
      name?: string | null; // String
      resourceId?: string | null; // String
    }
    readTextFile: { // args
      file: NexusGenScalars['File']; // File!
    }
    submitContactForm: { // args
      input: NexusGenInputs['SubmitContactFormInput']; // SubmitContactFormInput!
    }
    switchAccount: { // args
      accountId: string; // ID!
    }
    updateTranscript: { // args
      filename?: string | null; // String
      id: string; // String!
      words?: string | null; // String
    }
    upsertClip: { // args
      file: NexusGenScalars['File']; // File!
      originalClipId: string; // String!
      title?: string | null; // String
    }
  }
  Query: {
    node: { // args
      id: string; // ID!
    }
  }
  Subscription: {
    node: { // args
      id?: string | null; // ID
    }
  }
  BfCurrentViewer: {
    searchResults: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  BfCurrentViewer: "BfCurrentViewerAccessToken" | "BfCurrentViewerAnon"
  BfNode: "BfAccount" | "BfClip" | "BfClipReview" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaNodeTranscript" | "BfOrganization" | "BfPerson" | "BfSearchResult" | "BfSearchResultItem"
  BlogPostContentBlock: "CalloutBlock" | "CodeBlock" | "ImageBlock" | "ParagraphBlock"
  Node: "BfAccount" | "BfClip" | "BfClipReview" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaNodeTranscript" | "BfOrganization" | "BfPerson" | "BfSearchResult" | "BfSearchResultItem"
}

export interface NexusGenTypeInterfaces {
  BfAccount: "BfNode" | "Node"
  BfClip: "BfNode" | "Node"
  BfClipReview: "BfNode" | "Node"
  BfCurrentViewerAccessToken: "BfCurrentViewer"
  BfCurrentViewerAnon: "BfCurrentViewer"
  BfGoogleDriveResource: "BfNode" | "Node"
  BfMedia: "BfNode" | "Node"
  BfMediaNodeTranscript: "BfNode" | "Node"
  BfOrganization: "BfNode" | "Node"
  BfPerson: "BfNode" | "Node"
  BfSearchResult: "BfNode" | "Node"
  BfSearchResultItem: "BfNode" | "Node"
  CalloutBlock: "BlogPostContentBlock"
  CodeBlock: "BlogPostContentBlock"
  ImageBlock: "BlogPostContentBlock"
  ParagraphBlock: "BlogPostContentBlock"
  BfNode: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "BlogPostContentBlock";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}