/* @generated */
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "File";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Url";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "File";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Url";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SubmitContactFormInput: { // input type
    company?: string | null; // String
    email: string; // String!
    message: string; // String!
    name: string; // String!
    phone?: string | null; // String
  }
}

export interface NexusGenEnums {
  AccountRole: "ADMIN" | "ANON" | "OMNI" | "OWNER" | "REFRESH_CREDENTIALS_ONLY" | "SERVICE_INGESTION"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  File: File
  Url: string
}

export interface NexusGenObjects {
  BfAccount: { // root type
    displayName?: string | null; // String
    organizationBfGid?: string | null; // ID
    personBfGid?: string | null; // ID
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes?: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfClip: { // root type
    title?: string | null; // String
  }
  BfClipReview: { // root type
    mediaUrl?: NexusGenScalars['Url'] | null; // Url
    title?: string | null; // String
  }
  BfClipReviewConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfClipReviewEdge'] | null> | null; // [BfClipReviewEdge]
    nodes?: Array<NexusGenRootTypes['BfClipReview'] | null> | null; // [BfClipReview]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfClipReviewEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfClipReview'] | null; // BfClipReview
  }
  BfCurrentViewerAccessToken: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfCurrentViewerAnon: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfGoogleDriveResource: { // root type
    name?: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes?: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // root type
    filename?: string | null; // String
  }
  BfMediaConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes?: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaTranscript: { // root type
    filename?: string | null; // String
    words?: string | null; // String
  }
  BfMediaTranscriptConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaTranscriptEdge'] | null> | null; // [BfMediaTranscriptEdge]
    nodes?: Array<NexusGenRootTypes['BfMediaTranscript'] | null> | null; // [BfMediaTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaTranscriptEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMediaTranscript'] | null; // BfMediaTranscript
  }
  BfOrganization: { // root type
    id: string; // ID!
    name?: string | null; // String
  }
  BfPerson: { // root type
    email?: string | null; // String
    name?: string | null; // String
  }
  Blog: { // root type
    title?: string | null; // String
  }
  BlogPost: { // root type
    id?: string | null; // String
    slug?: string | null; // String
    title?: string | null; // String
  }
  BlogPostConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes?: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostContentBlock: { // root type
    id?: string | null; // String
    type?: string | null; // String
  }
  BlogPostContentBlockConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BlogPostContentBlockEdge'] | null> | null; // [BlogPostContentBlockEdge]
    nodes?: Array<NexusGenRootTypes['BlogPostContentBlock'] | null> | null; // [BlogPostContentBlock]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostContentBlockEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BlogPostContentBlock'] | null; // BlogPostContentBlock
  }
  BlogPostEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  DeleteMutationPayload: { // root type
    success: boolean; // Boolean!
  }
  DownloadMutationPayload: { // root type
    success: boolean; // Boolean!
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  SearchMutationPayload: { // root type
    message?: string | null; // String
    success: boolean; // Boolean!
  }
  SubmitContactFormPayload: { // root type
    message?: string | null; // String
    success: boolean; // Boolean!
  }
}

export interface NexusGenInterfaces {
  BfCurrentViewer: core.Discriminate<'BfCurrentViewerAccessToken', 'required'> | core.Discriminate<'BfCurrentViewerAnon', 'required'>;
  BfNode: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfClip', 'required'> | core.Discriminate<'BfClipReview', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'>;
  Node: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfClip', 'required'> | core.Discriminate<'BfClipReview', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'>;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  BfAccount: { // field return type
    displayName: string | null; // String
    id: string; // ID!
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    organizationBfGid: string | null; // ID
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    personBfGid: string | null; // ID
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfClip: { // field return type
    id: string; // ID!
    title: string | null; // String
  }
  BfClipReview: { // field return type
    id: string; // ID!
    mediaUrl: NexusGenScalars['Url'] | null; // Url
    title: string | null; // String
  }
  BfClipReviewConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfClipReviewEdge'] | null> | null; // [BfClipReviewEdge]
    nodes: Array<NexusGenRootTypes['BfClipReview'] | null> | null; // [BfClipReview]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfClipReviewEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfClipReview'] | null; // BfClipReview
  }
  BfCurrentViewerAccessToken: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfCurrentViewerAnon: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfGoogleDriveResource: { // field return type
    id: string; // ID!
    name: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // field return type
    filename: string | null; // String
    id: string; // ID!
    transcripts: NexusGenRootTypes['BfMediaTranscriptConnection'] | null; // BfMediaTranscriptConnection
  }
  BfMediaConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaTranscript: { // field return type
    filename: string | null; // String
    id: string; // ID!
    words: string | null; // String
  }
  BfMediaTranscriptConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaTranscriptEdge'] | null> | null; // [BfMediaTranscriptEdge]
    nodes: Array<NexusGenRootTypes['BfMediaTranscript'] | null> | null; // [BfMediaTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaTranscriptEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMediaTranscript'] | null; // BfMediaTranscript
  }
  BfOrganization: { // field return type
    googleDriveFolders: NexusGenRootTypes['BfGoogleDriveResourceConnection'] | null; // BfGoogleDriveResourceConnection
    id: string; // ID!
    media: NexusGenRootTypes['BfMediaConnection'] | null; // BfMediaConnection
    name: string | null; // String
    reviewableClips: NexusGenRootTypes['BfClipReviewConnection'] | null; // BfClipReviewConnection
  }
  BfPerson: { // field return type
    accounts: NexusGenRootTypes['BfAccountConnection'] | null; // BfAccountConnection
    email: string | null; // String
    googleAuthAccessToken: string | null; // String
    id: string; // ID!
    name: string | null; // String
  }
  Blog: { // field return type
    posts: NexusGenRootTypes['BlogPostConnection'] | null; // BlogPostConnection
    title: string | null; // String
  }
  BlogPost: { // field return type
    content: NexusGenRootTypes['BlogPostContentBlockConnection'] | null; // BlogPostContentBlockConnection
    id: string | null; // String
    slug: string | null; // String
    title: string | null; // String
  }
  BlogPostConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostContentBlock: { // field return type
    id: string | null; // String
    type: string | null; // String
  }
  BlogPostContentBlockConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BlogPostContentBlockEdge'] | null> | null; // [BlogPostContentBlockEdge]
    nodes: Array<NexusGenRootTypes['BlogPostContentBlock'] | null> | null; // [BlogPostContentBlock]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostContentBlockEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BlogPostContentBlock'] | null; // BlogPostContentBlock
  }
  BlogPostEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  DeleteMutationPayload: { // field return type
    success: boolean; // Boolean!
  }
  DownloadMutationPayload: { // field return type
    success: boolean; // Boolean!
  }
  Mutation: { // field return type
    createTranscript: NexusGenRootTypes['BfMediaTranscript'] | null; // BfMediaTranscript
    deleteGoogleDriveResource: NexusGenRootTypes['DeleteMutationPayload'] | null; // DeleteMutationPayload
    deleteTranscript: NexusGenRootTypes['BfMediaTranscript'] | null; // BfMediaTranscript
    downloadClip: NexusGenRootTypes['DownloadMutationPayload'] | null; // DownloadMutationPayload
    linkAdvancedGoogleAuth: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    loginWithGoogle: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    logout: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    pickGoogleDriveFolder: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
    readTextFile: string | null; // String
    searchMutation: NexusGenRootTypes['SearchMutationPayload'] | null; // SearchMutationPayload
    submitContactForm: NexusGenRootTypes['SubmitContactFormPayload'] | null; // SubmitContactFormPayload
    switchAccount: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    updateTranscript: NexusGenRootTypes['BfMediaTranscript'] | null; // BfMediaTranscript
    upsertClip: NexusGenRootTypes['BfClip'] | null; // BfClip
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    currentViewer: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  SearchMutationPayload: { // field return type
    message: string | null; // String
    success: boolean; // Boolean!
  }
  SubmitContactFormPayload: { // field return type
    message: string | null; // String
    success: boolean; // Boolean!
  }
  BfCurrentViewer: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfNode: { // field return type
    id: string; // ID!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  BfAccount: { // field return type name
    displayName: 'String'
    id: 'ID'
    organization: 'BfOrganization'
    organizationBfGid: 'ID'
    person: 'BfPerson'
    personBfGid: 'ID'
    role: 'AccountRole'
  }
  BfAccountConnection: { // field return type name
    count: 'Int'
    edges: 'BfAccountEdge'
    nodes: 'BfAccount'
    pageInfo: 'PageInfo'
  }
  BfAccountEdge: { // field return type name
    cursor: 'String'
    node: 'BfAccount'
  }
  BfClip: { // field return type name
    id: 'ID'
    title: 'String'
  }
  BfClipReview: { // field return type name
    id: 'ID'
    mediaUrl: 'Url'
    title: 'String'
  }
  BfClipReviewConnection: { // field return type name
    count: 'Int'
    edges: 'BfClipReviewEdge'
    nodes: 'BfClipReview'
    pageInfo: 'PageInfo'
  }
  BfClipReviewEdge: { // field return type name
    cursor: 'String'
    node: 'BfClipReview'
  }
  BfCurrentViewerAccessToken: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfCurrentViewerAnon: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfGoogleDriveResource: { // field return type name
    id: 'ID'
    name: 'String'
  }
  BfGoogleDriveResourceConnection: { // field return type name
    count: 'Int'
    edges: 'BfGoogleDriveResourceEdge'
    nodes: 'BfGoogleDriveResource'
    pageInfo: 'PageInfo'
  }
  BfGoogleDriveResourceEdge: { // field return type name
    cursor: 'String'
    node: 'BfGoogleDriveResource'
  }
  BfMedia: { // field return type name
    filename: 'String'
    id: 'ID'
    transcripts: 'BfMediaTranscriptConnection'
  }
  BfMediaConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaEdge'
    nodes: 'BfMedia'
    pageInfo: 'PageInfo'
  }
  BfMediaEdge: { // field return type name
    cursor: 'String'
    node: 'BfMedia'
  }
  BfMediaTranscript: { // field return type name
    filename: 'String'
    id: 'ID'
    words: 'String'
  }
  BfMediaTranscriptConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaTranscriptEdge'
    nodes: 'BfMediaTranscript'
    pageInfo: 'PageInfo'
  }
  BfMediaTranscriptEdge: { // field return type name
    cursor: 'String'
    node: 'BfMediaTranscript'
  }
  BfOrganization: { // field return type name
    googleDriveFolders: 'BfGoogleDriveResourceConnection'
    id: 'ID'
    media: 'BfMediaConnection'
    name: 'String'
    reviewableClips: 'BfClipReviewConnection'
  }
  BfPerson: { // field return type name
    accounts: 'BfAccountConnection'
    email: 'String'
    googleAuthAccessToken: 'String'
    id: 'ID'
    name: 'String'
  }
  Blog: { // field return type name
    posts: 'BlogPostConnection'
    title: 'String'
  }
  BlogPost: { // field return type name
    content: 'BlogPostContentBlockConnection'
    id: 'String'
    slug: 'String'
    title: 'String'
  }
  BlogPostConnection: { // field return type name
    count: 'Int'
    edges: 'BlogPostEdge'
    nodes: 'BlogPost'
    pageInfo: 'PageInfo'
  }
  BlogPostContentBlock: { // field return type name
    id: 'String'
    type: 'String'
  }
  BlogPostContentBlockConnection: { // field return type name
    count: 'Int'
    edges: 'BlogPostContentBlockEdge'
    nodes: 'BlogPostContentBlock'
    pageInfo: 'PageInfo'
  }
  BlogPostContentBlockEdge: { // field return type name
    cursor: 'String'
    node: 'BlogPostContentBlock'
  }
  BlogPostEdge: { // field return type name
    cursor: 'String'
    node: 'BlogPost'
  }
  DeleteMutationPayload: { // field return type name
    success: 'Boolean'
  }
  DownloadMutationPayload: { // field return type name
    success: 'Boolean'
  }
  Mutation: { // field return type name
    createTranscript: 'BfMediaTranscript'
    deleteGoogleDriveResource: 'DeleteMutationPayload'
    deleteTranscript: 'BfMediaTranscript'
    downloadClip: 'DownloadMutationPayload'
    linkAdvancedGoogleAuth: 'BfCurrentViewer'
    loginWithGoogle: 'BfCurrentViewerAccessToken'
    logout: 'BfCurrentViewer'
    pickGoogleDriveFolder: 'BfGoogleDriveResource'
    readTextFile: 'String'
    searchMutation: 'SearchMutationPayload'
    submitContactForm: 'SubmitContactFormPayload'
    switchAccount: 'BfCurrentViewerAccessToken'
    updateTranscript: 'BfMediaTranscript'
    upsertClip: 'BfClip'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    currentViewer: 'BfCurrentViewer'
    node: 'BfNode'
  }
  SearchMutationPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  SubmitContactFormPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  BfCurrentViewer: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfNode: { // field return type name
    id: 'ID'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  BfMedia: {
    transcripts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfOrganization: {
    googleDriveFolders: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    media: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    reviewableClips: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfPerson: {
    accounts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Blog: {
    posts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      slug?: string | null; // String
    }
  }
  BlogPost: {
    content: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    createTranscript: { // args
      filename: string; // String!
      words: string; // String!
    }
    deleteGoogleDriveResource: { // args
      resourceId?: string | null; // String
    }
    deleteTranscript: { // args
      id: string; // String!
    }
    downloadClip: { // args
      endTime: number; // Float!
      mediaId: string; // String!
      startTime: number; // Float!
      title: string; // String!
      transcriptId: string; // String!
    }
    linkAdvancedGoogleAuth: { // args
      code: string; // String!
    }
    loginWithGoogle: { // args
      credential: string; // String!
    }
    pickGoogleDriveFolder: { // args
      name?: string | null; // String
      resourceId?: string | null; // String
    }
    readTextFile: { // args
      file: NexusGenScalars['File']; // File!
    }
    searchMutation: { // args
      input: string; // String!
      suggestedModel?: string | null; // String
    }
    submitContactForm: { // args
      input: NexusGenInputs['SubmitContactFormInput']; // SubmitContactFormInput!
    }
    switchAccount: { // args
      accountId: string; // ID!
    }
    updateTranscript: { // args
      filename?: string | null; // String
      id: string; // String!
      words?: string | null; // String
    }
    upsertClip: { // args
      file: NexusGenScalars['File']; // File!
      originalClipId: string; // String!
      title?: string | null; // String
    }
  }
  Query: {
    node: { // args
      id: string; // ID!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  BfCurrentViewer: "BfCurrentViewerAccessToken" | "BfCurrentViewerAnon"
  BfNode: "BfAccount" | "BfClip" | "BfClipReview" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaTranscript" | "BfOrganization" | "BfPerson"
  Node: "BfAccount" | "BfClip" | "BfClipReview" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaTranscript" | "BfOrganization" | "BfPerson"
}

export interface NexusGenTypeInterfaces {
  BfAccount: "BfNode" | "Node"
  BfClip: "BfNode" | "Node"
  BfClipReview: "BfNode" | "Node"
  BfCurrentViewerAccessToken: "BfCurrentViewer"
  BfCurrentViewerAnon: "BfCurrentViewer"
  BfGoogleDriveResource: "BfNode" | "Node"
  BfMedia: "BfNode" | "Node"
  BfMediaTranscript: "BfNode" | "Node"
  BfOrganization: "BfNode" | "Node"
  BfPerson: "BfNode" | "Node"
  BfNode: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}