/* @generated */
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "File";
    /**
     * Timecode described as milliseconds
     */
    msTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "TimecodeInMilliseconds";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Url";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `File` scalar type represents a file upload.
     */
    file<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "File";
    /**
     * Timecode described as milliseconds
     */
    msTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "TimecodeInMilliseconds";
    /**
     * a fully qualified URL
     */
    url<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Url";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  SubmitContactFormInput: { // input type
    company?: string | null; // String
    email: string; // String!
    message: string; // String!
    name: string; // String!
    phone?: string | null; // String
  }
}

export interface NexusGenEnums {
  AccountRole: "ADMIN" | "ANON" | "MEMBER" | "OMNI" | "OWNER" | "REFRESH_CREDENTIALS_ONLY" | "SERVICE_INGESTION"
  PostStatus: "Dev only" | "Ready for publish" | "Workshop"
  SearchStatus: "COMPLETED" | "ERRORED" | "PENDING" | "RUNNING"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  File: File
  TimecodeInMilliseconds: int
  Url: string
}

export interface NexusGenObjects {
  Annotations: { // root type
    bold?: boolean | null; // Boolean
    code?: boolean | null; // Boolean
    color?: string | null; // String
    italic?: boolean | null; // Boolean
    strikethrough?: boolean | null; // Boolean
    underlined?: boolean | null; // Boolean
  }
  AssemblyAIWord: { // root type
    confidence?: number | null; // Float
    end?: number | null; // Int
    speaker?: string | null; // String
    start?: number | null; // Int
    text?: string | null; // String
    word?: string | null; // String
  }
  BfAccount: { // root type
    displayName?: string | null; // String
    organizationBfGid?: string | null; // ID
    personBfGid?: string | null; // ID
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes?: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfCollection: { // root type
    name?: string | null; // String
  }
  BfCollectionConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfCollectionEdge'] | null> | null; // [BfCollectionEdge]
    nodes?: Array<NexusGenRootTypes['BfCollection'] | null> | null; // [BfCollection]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfCollectionEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfCollection'] | null; // BfCollection
  }
  BfConnectionEdge: { // root type
    cursor?: string | null; // String
    node?: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  BfConnectionSubscriptionPayload: { // root type
    append?: NexusGenRootTypes['BfConnectionEdge'] | null; // BfConnectionEdge
  }
  BfCurrentViewerAccessToken: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfCurrentViewerAnon: { // root type
    role?: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfGoogleDriveResource: { // root type
    name?: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes?: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // root type
    fileId?: string | null; // String
    filename?: string | null; // String
    name?: string | null; // String
  }
  BfMediaConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes?: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaNodeTranscript: { // root type
    filename?: string | null; // String
    words?: Array<NexusGenRootTypes['AssemblyAIWord'] | null> | null; // [AssemblyAIWord]
  }
  BfMediaNodeTranscriptConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfMediaNodeTranscriptEdge'] | null> | null; // [BfMediaNodeTranscriptEdge]
    nodes?: Array<NexusGenRootTypes['BfMediaNodeTranscript'] | null> | null; // [BfMediaNodeTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaNodeTranscriptEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
  }
  BfOrganization: { // root type
    id: string; // ID!
    name?: string | null; // String
  }
  BfPerson: { // root type
    email?: string | null; // String
    name?: string | null; // String
  }
  BfSavedSearch: { // root type
    query?: string | null; // String
  }
  BfSavedSearchConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfSavedSearchEdge'] | null> | null; // [BfSavedSearchEdge]
    nodes?: Array<NexusGenRootTypes['BfSavedSearch'] | null> | null; // [BfSavedSearch]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSavedSearchEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfSavedSearch'] | null; // BfSavedSearch
  }
  BfSavedSearchResult: { // root type
    body?: string | null; // String
    confidence?: number | null; // Float
    description?: string | null; // String
    duration?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    endTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    rationale?: string | null; // String
    startTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    title?: string | null; // String
    topics?: Array<string | null> | null; // [String]
    verbatim?: boolean | null; // Boolean
  }
  BfSavedSearchResultConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfSavedSearchResultEdge'] | null> | null; // [BfSavedSearchResultEdge]
    nodes?: Array<NexusGenRootTypes['BfSavedSearchResult'] | null> | null; // [BfSavedSearchResult]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSavedSearchResultEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfSavedSearchResult'] | null; // BfSavedSearchResult
  }
  BfTTGame: { // root type
    correctResponses?: number | null; // Int
    incorrectResponses?: number | null; // Int
  }
  BfTTQuestion: { // root type
    category?: string | null; // String
    correct_answer?: string | null; // String
    difficulty?: string | null; // String
    incorrect_answers?: Array<string | null> | null; // [String]
    question?: string | null; // String
    type?: string | null; // String
  }
  BfTTQuestionConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BfTTQuestionEdge'] | null> | null; // [BfTTQuestionEdge]
    nodes?: Array<NexusGenRootTypes['BfTTQuestion'] | null> | null; // [BfTTQuestion]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfTTQuestionEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BfTTQuestion'] | null; // BfTTQuestion
  }
  Blog: { // root type
    title?: string | null; // String
  }
  BlogPost: { // root type
    callToAction?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    coverUrl?: string | null; // String
    icon?: string | null; // String
    id: string; // String!
    slug?: string | null; // String
    status?: NexusGenEnums['PostStatus'] | null; // PostStatus
    summary?: string | null; // String
    title?: string | null; // String
  }
  BlogPostAuthor: { // root type
    avatarUrl?: string | null; // String
    email?: string | null; // String
    name?: string | null; // String
  }
  BlogPostConnection: { // root type
    count?: number | null; // Int
    edges?: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes?: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  CalloutBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color?: string | null; // String
    icon?: string | null; // String
    id?: string | null; // String
    type?: string | null; // String
  }
  CodeBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id?: string | null; // String
    language?: string | null; // String
    type?: string | null; // String
  }
  HeadingBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color?: string | null; // String
    id?: string | null; // String
    isToggleable?: boolean | null; // Boolean
    size?: string | null; // String
    type?: string | null; // String
  }
  ImageBlock: { // root type
    caption?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id?: string | null; // String
    imgUrl?: string | null; // String
    type?: string | null; // String
  }
  Link: { // root type
    url?: string | null; // String
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  ParagraphBlock: { // root type
    RichText?: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color?: string | null; // String
    id?: string | null; // String
    type?: string | null; // String
  }
  Query: {};
  RichText: { // root type
    annotations?: NexusGenRootTypes['Annotations'] | null; // Annotations
    text?: NexusGenRootTypes['Text'] | null; // Text
    type?: string | null; // String
  }
  SubmitContactFormPayload: { // root type
    message?: string | null; // String
    success: boolean; // Boolean!
  }
  Subscription: {};
  Text: { // root type
    content?: string | null; // String
    link?: NexusGenRootTypes['Link'] | null; // Link
  }
  VideoDownloadable: { // root type
    duration?: number | null; // Int
    percentageRendered?: number | null; // Float
    ready?: boolean | null; // Boolean
    url?: NexusGenScalars['Url'] | null; // Url
  }
  VideoPreviewable: { // root type
    duration?: number | null; // Int
    url?: NexusGenScalars['Url'] | null; // Url
  }
  Word: { // root type
    endTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    speaker?: string | null; // String
    startTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    text?: string | null; // String
  }
}

export interface NexusGenInterfaces {
  BfCurrentViewer: core.Discriminate<'BfCurrentViewerAccessToken', 'required'> | core.Discriminate<'BfCurrentViewerAnon', 'required'>;
  BfNode: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfCollection', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaNodeTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'> | core.Discriminate<'BfSavedSearch', 'required'> | core.Discriminate<'BfSavedSearchResult', 'required'> | core.Discriminate<'BfTTGame', 'required'> | core.Discriminate<'BfTTQuestion', 'required'>;
  BlogPostContentBlock: core.Discriminate<'CalloutBlock', 'optional'> | core.Discriminate<'CodeBlock', 'optional'> | core.Discriminate<'HeadingBlock', 'optional'> | core.Discriminate<'ImageBlock', 'optional'> | core.Discriminate<'ParagraphBlock', 'optional'>;
  Media: core.Discriminate<'VideoDownloadable', 'required'> | core.Discriminate<'VideoPreviewable', 'required'>;
  Node: core.Discriminate<'BfAccount', 'required'> | core.Discriminate<'BfCollection', 'required'> | core.Discriminate<'BfGoogleDriveResource', 'required'> | core.Discriminate<'BfMedia', 'required'> | core.Discriminate<'BfMediaNodeTranscript', 'required'> | core.Discriminate<'BfOrganization', 'required'> | core.Discriminate<'BfPerson', 'required'> | core.Discriminate<'BfSavedSearch', 'required'> | core.Discriminate<'BfSavedSearchResult', 'required'> | core.Discriminate<'BfTTGame', 'required'> | core.Discriminate<'BfTTQuestion', 'required'>;
  Video: core.Discriminate<'VideoDownloadable', 'required'> | core.Discriminate<'VideoPreviewable', 'required'>;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Annotations: { // field return type
    bold: boolean | null; // Boolean
    code: boolean | null; // Boolean
    color: string | null; // String
    italic: boolean | null; // Boolean
    strikethrough: boolean | null; // Boolean
    underlined: boolean | null; // Boolean
  }
  AssemblyAIWord: { // field return type
    confidence: number | null; // Float
    end: number | null; // Int
    speaker: string | null; // String
    start: number | null; // Int
    text: string | null; // String
    word: string | null; // String
  }
  BfAccount: { // field return type
    displayName: string | null; // String
    id: string; // ID!
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    organizationBfGid: string | null; // ID
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    personBfGid: string | null; // ID
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfAccountConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfAccountEdge'] | null> | null; // [BfAccountEdge]
    nodes: Array<NexusGenRootTypes['BfAccount'] | null> | null; // [BfAccount]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfAccountEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfAccount'] | null; // BfAccount
  }
  BfCollection: { // field return type
    id: string; // ID!
    media: NexusGenRootTypes['BfMediaConnection'] | null; // BfMediaConnection
    name: string | null; // String
    watchedFolders: NexusGenRootTypes['BfGoogleDriveResourceConnection'] | null; // BfGoogleDriveResourceConnection
  }
  BfCollectionConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfCollectionEdge'] | null> | null; // [BfCollectionEdge]
    nodes: Array<NexusGenRootTypes['BfCollection'] | null> | null; // [BfCollection]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfCollectionEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfCollection'] | null; // BfCollection
  }
  BfConnectionEdge: { // field return type
    cursor: string | null; // String
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  BfConnectionSubscriptionPayload: { // field return type
    append: NexusGenRootTypes['BfConnectionEdge'] | null; // BfConnectionEdge
  }
  BfCurrentViewerAccessToken: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfCurrentViewerAnon: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfGoogleDriveResource: { // field return type
    id: string; // ID!
    name: string | null; // String
  }
  BfGoogleDriveResourceConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfGoogleDriveResourceEdge'] | null> | null; // [BfGoogleDriveResourceEdge]
    nodes: Array<NexusGenRootTypes['BfGoogleDriveResource'] | null> | null; // [BfGoogleDriveResource]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfGoogleDriveResourceEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
  }
  BfMedia: { // field return type
    fileId: string | null; // String
    filename: string | null; // String
    id: string; // ID!
    name: string | null; // String
    previewVideoUrl: string | null; // String
    transcripts: NexusGenRootTypes['BfMediaNodeTranscriptConnection'] | null; // BfMediaNodeTranscriptConnection
  }
  BfMediaConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaEdge'] | null> | null; // [BfMediaEdge]
    nodes: Array<NexusGenRootTypes['BfMedia'] | null> | null; // [BfMedia]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMedia'] | null; // BfMedia
  }
  BfMediaNodeTranscript: { // field return type
    filename: string | null; // String
    id: string; // ID!
    words: Array<NexusGenRootTypes['AssemblyAIWord'] | null> | null; // [AssemblyAIWord]
  }
  BfMediaNodeTranscriptConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfMediaNodeTranscriptEdge'] | null> | null; // [BfMediaNodeTranscriptEdge]
    nodes: Array<NexusGenRootTypes['BfMediaNodeTranscript'] | null> | null; // [BfMediaNodeTranscript]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfMediaNodeTranscriptEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
  }
  BfOrganization: { // field return type
    collections: NexusGenRootTypes['BfCollectionConnection'] | null; // BfCollectionConnection
    defaultCollection: NexusGenRootTypes['BfCollection'] | null; // BfCollection
    googleDriveFolders: NexusGenRootTypes['BfGoogleDriveResourceConnection'] | null; // BfGoogleDriveResourceConnection
    id: string; // ID!
    media: NexusGenRootTypes['BfMediaConnection'] | null; // BfMediaConnection
    name: string | null; // String
    savedSearches: NexusGenRootTypes['BfSavedSearchConnection'] | null; // BfSavedSearchConnection
  }
  BfPerson: { // field return type
    accounts: NexusGenRootTypes['BfAccountConnection'] | null; // BfAccountConnection
    email: string | null; // String
    googleAuthAccessToken: string | null; // String
    id: string; // ID!
    name: string | null; // String
  }
  BfSavedSearch: { // field return type
    id: string; // ID!
    query: string | null; // String
    searchResults: NexusGenRootTypes['BfSavedSearchResultConnection'] | null; // BfSavedSearchResultConnection
  }
  BfSavedSearchConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfSavedSearchEdge'] | null> | null; // [BfSavedSearchEdge]
    nodes: Array<NexusGenRootTypes['BfSavedSearch'] | null> | null; // [BfSavedSearch]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSavedSearchEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfSavedSearch'] | null; // BfSavedSearch
  }
  BfSavedSearchResult: { // field return type
    body: string | null; // String
    confidence: number | null; // Float
    description: string | null; // String
    downloadable: NexusGenRootTypes['VideoDownloadable'] | null; // VideoDownloadable
    duration: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    endTime: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    id: string; // ID!
    previewable: NexusGenRootTypes['VideoPreviewable'] | null; // VideoPreviewable
    rationale: string | null; // String
    startTime: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    title: string | null; // String
    topics: Array<string | null> | null; // [String]
    verbatim: boolean | null; // Boolean
    words: Array<NexusGenRootTypes['Word'] | null> | null; // [Word]
  }
  BfSavedSearchResultConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfSavedSearchResultEdge'] | null> | null; // [BfSavedSearchResultEdge]
    nodes: Array<NexusGenRootTypes['BfSavedSearchResult'] | null> | null; // [BfSavedSearchResult]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfSavedSearchResultEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfSavedSearchResult'] | null; // BfSavedSearchResult
  }
  BfTTGame: { // field return type
    correctResponses: number | null; // Int
    id: string; // ID!
    incorrectResponses: number | null; // Int
    questions: NexusGenRootTypes['BfTTQuestionConnection'] | null; // BfTTQuestionConnection
  }
  BfTTQuestion: { // field return type
    category: string | null; // String
    correct_answer: string | null; // String
    difficulty: string | null; // String
    id: string; // ID!
    incorrect_answers: Array<string | null> | null; // [String]
    question: string | null; // String
    type: string | null; // String
  }
  BfTTQuestionConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BfTTQuestionEdge'] | null> | null; // [BfTTQuestionEdge]
    nodes: Array<NexusGenRootTypes['BfTTQuestion'] | null> | null; // [BfTTQuestion]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BfTTQuestionEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BfTTQuestion'] | null; // BfTTQuestion
  }
  Blog: { // field return type
    posts: NexusGenRootTypes['BlogPostConnection'] | null; // BlogPostConnection
    title: string | null; // String
  }
  BlogPost: { // field return type
    author: NexusGenRootTypes['BlogPostAuthor'] | null; // BlogPostAuthor
    callToAction: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    content: Array<NexusGenRootTypes['BlogPostContentBlock'] | null> | null; // [BlogPostContentBlock]
    coverUrl: string | null; // String
    date: string | null; // String
    icon: string | null; // String
    id: string; // String!
    slug: string | null; // String
    status: NexusGenEnums['PostStatus'] | null; // PostStatus
    summary: string | null; // String
    title: string | null; // String
  }
  BlogPostAuthor: { // field return type
    avatarUrl: string | null; // String
    email: string | null; // String
    name: string | null; // String
  }
  BlogPostConnection: { // field return type
    count: number | null; // Int
    edges: Array<NexusGenRootTypes['BlogPostEdge'] | null> | null; // [BlogPostEdge]
    nodes: Array<NexusGenRootTypes['BlogPost'] | null> | null; // [BlogPost]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  BlogPostEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['BlogPost'] | null; // BlogPost
  }
  CalloutBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color: string | null; // String
    icon: string | null; // String
    id: string | null; // String
    type: string | null; // String
  }
  CodeBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id: string | null; // String
    language: string | null; // String
    type: string | null; // String
  }
  HeadingBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color: string | null; // String
    id: string | null; // String
    isToggleable: boolean | null; // Boolean
    size: string | null; // String
    type: string | null; // String
  }
  ImageBlock: { // field return type
    caption: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    id: string | null; // String
    imgUrl: string | null; // String
    type: string | null; // String
  }
  Link: { // field return type
    url: string | null; // String
  }
  Mutation: { // field return type
    addFolderToCollection: NexusGenRootTypes['BfCollection'] | null; // BfCollection
    createTTGame: NexusGenRootTypes['BfTTGame'] | null; // BfTTGame
    createTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
    deleteGoogleDriveResource: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
    deleteMedia: NexusGenRootTypes['BfMedia'] | null; // BfMedia
    deleteTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
    linkAdvancedGoogleAuth: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    loginWithGoogle: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    logout: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    pickGoogleDriveFolder: NexusGenRootTypes['BfGoogleDriveResource'] | null; // BfGoogleDriveResource
    readTextFile: string | null; // String
    searchCollection: NexusGenRootTypes['BfSavedSearch'] | null; // BfSavedSearch
    submitContactForm: NexusGenRootTypes['SubmitContactFormPayload'] | null; // SubmitContactFormPayload
    switchAccount: NexusGenRootTypes['BfCurrentViewerAccessToken'] | null; // BfCurrentViewerAccessToken
    updateTTGameScore: NexusGenRootTypes['BfTTGame'] | null; // BfTTGame
    updateTranscript: NexusGenRootTypes['BfMediaNodeTranscript'] | null; // BfMediaNodeTranscript
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  ParagraphBlock: { // field return type
    RichText: Array<NexusGenRootTypes['RichText'] | null> | null; // [RichText]
    color: string | null; // String
    id: string | null; // String
    type: string | null; // String
  }
  Query: { // field return type
    currentViewer: NexusGenRootTypes['BfCurrentViewer'] | null; // BfCurrentViewer
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  RichText: { // field return type
    annotations: NexusGenRootTypes['Annotations'] | null; // Annotations
    text: NexusGenRootTypes['Text'] | null; // Text
    type: string | null; // String
  }
  SubmitContactFormPayload: { // field return type
    message: string | null; // String
    success: boolean; // Boolean!
  }
  Subscription: { // field return type
    connection: NexusGenRootTypes['BfConnectionSubscriptionPayload'] | null; // BfConnectionSubscriptionPayload
    node: NexusGenRootTypes['BfNode'] | null; // BfNode
  }
  Text: { // field return type
    content: string | null; // String
    link: NexusGenRootTypes['Link'] | null; // Link
  }
  VideoDownloadable: { // field return type
    duration: number | null; // Int
    percentageRendered: number | null; // Float
    ready: boolean | null; // Boolean
    url: NexusGenScalars['Url'] | null; // Url
  }
  VideoPreviewable: { // field return type
    duration: number | null; // Int
    url: NexusGenScalars['Url'] | null; // Url
  }
  Word: { // field return type
    endTime: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    speaker: string | null; // String
    startTime: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    text: string | null; // String
  }
  BfCurrentViewer: { // field return type
    blog: NexusGenRootTypes['Blog'] | null; // Blog
    organization: NexusGenRootTypes['BfOrganization'] | null; // BfOrganization
    person: NexusGenRootTypes['BfPerson'] | null; // BfPerson
    role: NexusGenEnums['AccountRole'] | null; // AccountRole
  }
  BfNode: { // field return type
    id: string; // ID!
  }
  BlogPostContentBlock: { // field return type
    id: string | null; // String
    type: string | null; // String
  }
  Media: { // field return type
    duration: number | null; // Int
    url: NexusGenScalars['Url'] | null; // Url
  }
  Node: { // field return type
    id: string; // ID!
  }
  Video: { // field return type
    duration: number | null; // Int
    url: NexusGenScalars['Url'] | null; // Url
  }
}

export interface NexusGenFieldTypeNames {
  Annotations: { // field return type name
    bold: 'Boolean'
    code: 'Boolean'
    color: 'String'
    italic: 'Boolean'
    strikethrough: 'Boolean'
    underlined: 'Boolean'
  }
  AssemblyAIWord: { // field return type name
    confidence: 'Float'
    end: 'Int'
    speaker: 'String'
    start: 'Int'
    text: 'String'
    word: 'String'
  }
  BfAccount: { // field return type name
    displayName: 'String'
    id: 'ID'
    organization: 'BfOrganization'
    organizationBfGid: 'ID'
    person: 'BfPerson'
    personBfGid: 'ID'
    role: 'AccountRole'
  }
  BfAccountConnection: { // field return type name
    count: 'Int'
    edges: 'BfAccountEdge'
    nodes: 'BfAccount'
    pageInfo: 'PageInfo'
  }
  BfAccountEdge: { // field return type name
    cursor: 'String'
    node: 'BfAccount'
  }
  BfCollection: { // field return type name
    id: 'ID'
    media: 'BfMediaConnection'
    name: 'String'
    watchedFolders: 'BfGoogleDriveResourceConnection'
  }
  BfCollectionConnection: { // field return type name
    count: 'Int'
    edges: 'BfCollectionEdge'
    nodes: 'BfCollection'
    pageInfo: 'PageInfo'
  }
  BfCollectionEdge: { // field return type name
    cursor: 'String'
    node: 'BfCollection'
  }
  BfConnectionEdge: { // field return type name
    cursor: 'String'
    node: 'BfNode'
  }
  BfConnectionSubscriptionPayload: { // field return type name
    append: 'BfConnectionEdge'
  }
  BfCurrentViewerAccessToken: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfCurrentViewerAnon: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfGoogleDriveResource: { // field return type name
    id: 'ID'
    name: 'String'
  }
  BfGoogleDriveResourceConnection: { // field return type name
    count: 'Int'
    edges: 'BfGoogleDriveResourceEdge'
    nodes: 'BfGoogleDriveResource'
    pageInfo: 'PageInfo'
  }
  BfGoogleDriveResourceEdge: { // field return type name
    cursor: 'String'
    node: 'BfGoogleDriveResource'
  }
  BfMedia: { // field return type name
    fileId: 'String'
    filename: 'String'
    id: 'ID'
    name: 'String'
    previewVideoUrl: 'String'
    transcripts: 'BfMediaNodeTranscriptConnection'
  }
  BfMediaConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaEdge'
    nodes: 'BfMedia'
    pageInfo: 'PageInfo'
  }
  BfMediaEdge: { // field return type name
    cursor: 'String'
    node: 'BfMedia'
  }
  BfMediaNodeTranscript: { // field return type name
    filename: 'String'
    id: 'ID'
    words: 'AssemblyAIWord'
  }
  BfMediaNodeTranscriptConnection: { // field return type name
    count: 'Int'
    edges: 'BfMediaNodeTranscriptEdge'
    nodes: 'BfMediaNodeTranscript'
    pageInfo: 'PageInfo'
  }
  BfMediaNodeTranscriptEdge: { // field return type name
    cursor: 'String'
    node: 'BfMediaNodeTranscript'
  }
  BfOrganization: { // field return type name
    collections: 'BfCollectionConnection'
    defaultCollection: 'BfCollection'
    googleDriveFolders: 'BfGoogleDriveResourceConnection'
    id: 'ID'
    media: 'BfMediaConnection'
    name: 'String'
    savedSearches: 'BfSavedSearchConnection'
  }
  BfPerson: { // field return type name
    accounts: 'BfAccountConnection'
    email: 'String'
    googleAuthAccessToken: 'String'
    id: 'ID'
    name: 'String'
  }
  BfSavedSearch: { // field return type name
    id: 'ID'
    query: 'String'
    searchResults: 'BfSavedSearchResultConnection'
  }
  BfSavedSearchConnection: { // field return type name
    count: 'Int'
    edges: 'BfSavedSearchEdge'
    nodes: 'BfSavedSearch'
    pageInfo: 'PageInfo'
  }
  BfSavedSearchEdge: { // field return type name
    cursor: 'String'
    node: 'BfSavedSearch'
  }
  BfSavedSearchResult: { // field return type name
    body: 'String'
    confidence: 'Float'
    description: 'String'
    downloadable: 'VideoDownloadable'
    duration: 'TimecodeInMilliseconds'
    endTime: 'TimecodeInMilliseconds'
    id: 'ID'
    previewable: 'VideoPreviewable'
    rationale: 'String'
    startTime: 'TimecodeInMilliseconds'
    title: 'String'
    topics: 'String'
    verbatim: 'Boolean'
    words: 'Word'
  }
  BfSavedSearchResultConnection: { // field return type name
    count: 'Int'
    edges: 'BfSavedSearchResultEdge'
    nodes: 'BfSavedSearchResult'
    pageInfo: 'PageInfo'
  }
  BfSavedSearchResultEdge: { // field return type name
    cursor: 'String'
    node: 'BfSavedSearchResult'
  }
  BfTTGame: { // field return type name
    correctResponses: 'Int'
    id: 'ID'
    incorrectResponses: 'Int'
    questions: 'BfTTQuestionConnection'
  }
  BfTTQuestion: { // field return type name
    category: 'String'
    correct_answer: 'String'
    difficulty: 'String'
    id: 'ID'
    incorrect_answers: 'String'
    question: 'String'
    type: 'String'
  }
  BfTTQuestionConnection: { // field return type name
    count: 'Int'
    edges: 'BfTTQuestionEdge'
    nodes: 'BfTTQuestion'
    pageInfo: 'PageInfo'
  }
  BfTTQuestionEdge: { // field return type name
    cursor: 'String'
    node: 'BfTTQuestion'
  }
  Blog: { // field return type name
    posts: 'BlogPostConnection'
    title: 'String'
  }
  BlogPost: { // field return type name
    author: 'BlogPostAuthor'
    callToAction: 'RichText'
    content: 'BlogPostContentBlock'
    coverUrl: 'String'
    date: 'String'
    icon: 'String'
    id: 'String'
    slug: 'String'
    status: 'PostStatus'
    summary: 'String'
    title: 'String'
  }
  BlogPostAuthor: { // field return type name
    avatarUrl: 'String'
    email: 'String'
    name: 'String'
  }
  BlogPostConnection: { // field return type name
    count: 'Int'
    edges: 'BlogPostEdge'
    nodes: 'BlogPost'
    pageInfo: 'PageInfo'
  }
  BlogPostEdge: { // field return type name
    cursor: 'String'
    node: 'BlogPost'
  }
  CalloutBlock: { // field return type name
    RichText: 'RichText'
    color: 'String'
    icon: 'String'
    id: 'String'
    type: 'String'
  }
  CodeBlock: { // field return type name
    RichText: 'RichText'
    id: 'String'
    language: 'String'
    type: 'String'
  }
  HeadingBlock: { // field return type name
    RichText: 'RichText'
    color: 'String'
    id: 'String'
    isToggleable: 'Boolean'
    size: 'String'
    type: 'String'
  }
  ImageBlock: { // field return type name
    caption: 'RichText'
    id: 'String'
    imgUrl: 'String'
    type: 'String'
  }
  Link: { // field return type name
    url: 'String'
  }
  Mutation: { // field return type name
    addFolderToCollection: 'BfCollection'
    createTTGame: 'BfTTGame'
    createTranscript: 'BfMediaNodeTranscript'
    deleteGoogleDriveResource: 'BfGoogleDriveResource'
    deleteMedia: 'BfMedia'
    deleteTranscript: 'BfMediaNodeTranscript'
    linkAdvancedGoogleAuth: 'BfCurrentViewer'
    loginWithGoogle: 'BfCurrentViewerAccessToken'
    logout: 'BfCurrentViewer'
    pickGoogleDriveFolder: 'BfGoogleDriveResource'
    readTextFile: 'String'
    searchCollection: 'BfSavedSearch'
    submitContactForm: 'SubmitContactFormPayload'
    switchAccount: 'BfCurrentViewerAccessToken'
    updateTTGameScore: 'BfTTGame'
    updateTranscript: 'BfMediaNodeTranscript'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  ParagraphBlock: { // field return type name
    RichText: 'RichText'
    color: 'String'
    id: 'String'
    type: 'String'
  }
  Query: { // field return type name
    currentViewer: 'BfCurrentViewer'
    node: 'BfNode'
  }
  RichText: { // field return type name
    annotations: 'Annotations'
    text: 'Text'
    type: 'String'
  }
  SubmitContactFormPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  Subscription: { // field return type name
    connection: 'BfConnectionSubscriptionPayload'
    node: 'BfNode'
  }
  Text: { // field return type name
    content: 'String'
    link: 'Link'
  }
  VideoDownloadable: { // field return type name
    duration: 'Int'
    percentageRendered: 'Float'
    ready: 'Boolean'
    url: 'Url'
  }
  VideoPreviewable: { // field return type name
    duration: 'Int'
    url: 'Url'
  }
  Word: { // field return type name
    endTime: 'TimecodeInMilliseconds'
    speaker: 'String'
    startTime: 'TimecodeInMilliseconds'
    text: 'String'
  }
  BfCurrentViewer: { // field return type name
    blog: 'Blog'
    organization: 'BfOrganization'
    person: 'BfPerson'
    role: 'AccountRole'
  }
  BfNode: { // field return type name
    id: 'ID'
  }
  BlogPostContentBlock: { // field return type name
    id: 'String'
    type: 'String'
  }
  Media: { // field return type name
    duration: 'Int'
    url: 'Url'
  }
  Node: { // field return type name
    id: 'ID'
  }
  Video: { // field return type name
    duration: 'Int'
    url: 'Url'
  }
}

export interface NexusGenArgTypes {
  BfCollection: {
    media: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    watchedFolders: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfMedia: {
    transcripts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfOrganization: {
    collections: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    googleDriveFolders: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    media: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
    savedSearches: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfPerson: {
    accounts: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfSavedSearch: {
    searchResults: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  BfSavedSearchResult: {
    words: { // args
      endTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
      startTime?: NexusGenScalars['TimecodeInMilliseconds'] | null; // TimecodeInMilliseconds
    }
  }
  BfTTGame: {
    questions: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Blog: {
    posts: { // args
      after?: string | null; // String
      author?: string | null; // String
      before?: string | null; // String
      date?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      slug?: string | null; // String
      status?: Array<NexusGenEnums['PostStatus'] | null> | null; // [PostStatus]
    }
  }
  Mutation: {
    addFolderToCollection: { // args
      googleDriveResourceId: string; // String!
      name: string; // String!
    }
    createTTGame: { // args
      shouldCreate?: boolean | null; // Boolean
    }
    createTranscript: { // args
      filename: string; // String!
      words: string; // String!
    }
    deleteGoogleDriveResource: { // args
      resourceId?: string | null; // String
    }
    deleteMedia: { // args
      id: string; // String!
    }
    deleteTranscript: { // args
      id: string; // String!
    }
    linkAdvancedGoogleAuth: { // args
      code: string; // String!
    }
    loginWithGoogle: { // args
      credential: string; // String!
    }
    pickGoogleDriveFolder: { // args
      name?: string | null; // String
      resourceId?: string | null; // String
    }
    readTextFile: { // args
      file: NexusGenScalars['File']; // File!
    }
    searchCollection: { // args
      collectionId: string; // ID!
      query: string; // String!
    }
    submitContactForm: { // args
      input: NexusGenInputs['SubmitContactFormInput']; // SubmitContactFormInput!
    }
    switchAccount: { // args
      accountId: string; // ID!
    }
    updateTTGameScore: { // args
      respondedCorrectly: boolean; // Boolean!
    }
    updateTranscript: { // args
      filename?: string | null; // String
      id: string; // String!
      words?: string | null; // String
    }
  }
  Query: {
    node: { // args
      id: string; // ID!
    }
  }
  Subscription: {
    connection: { // args
      id?: string | null; // ID
      targetClassName?: string | null; // String
    }
    node: { // args
      id?: string | null; // ID
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  BfCurrentViewer: "BfCurrentViewerAccessToken" | "BfCurrentViewerAnon"
  BfNode: "BfAccount" | "BfCollection" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaNodeTranscript" | "BfOrganization" | "BfPerson" | "BfSavedSearch" | "BfSavedSearchResult" | "BfTTGame" | "BfTTQuestion"
  BlogPostContentBlock: "CalloutBlock" | "CodeBlock" | "HeadingBlock" | "ImageBlock" | "ParagraphBlock"
  Media: "VideoDownloadable" | "VideoPreviewable"
  Node: "BfAccount" | "BfCollection" | "BfGoogleDriveResource" | "BfMedia" | "BfMediaNodeTranscript" | "BfOrganization" | "BfPerson" | "BfSavedSearch" | "BfSavedSearchResult" | "BfTTGame" | "BfTTQuestion"
  Video: "VideoDownloadable" | "VideoPreviewable"
}

export interface NexusGenTypeInterfaces {
  BfAccount: "BfNode" | "Node"
  BfCollection: "BfNode" | "Node"
  BfCurrentViewerAccessToken: "BfCurrentViewer"
  BfCurrentViewerAnon: "BfCurrentViewer"
  BfGoogleDriveResource: "BfNode" | "Node"
  BfMedia: "BfNode" | "Node"
  BfMediaNodeTranscript: "BfNode" | "Node"
  BfOrganization: "BfNode" | "Node"
  BfPerson: "BfNode" | "Node"
  BfSavedSearch: "BfNode" | "Node"
  BfSavedSearchResult: "BfNode" | "Node"
  BfTTGame: "BfNode" | "Node"
  BfTTQuestion: "BfNode" | "Node"
  CalloutBlock: "BlogPostContentBlock"
  CodeBlock: "BlogPostContentBlock"
  HeadingBlock: "BlogPostContentBlock"
  ImageBlock: "BlogPostContentBlock"
  ParagraphBlock: "BlogPostContentBlock"
  VideoDownloadable: "Media" | "Video"
  VideoPreviewable: "Media" | "Video"
  BfNode: "Node"
  Video: "Media"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "BlogPostContentBlock";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}