#cloud-config
packages:
  - docker.io
  - docker-compose

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker root
  # Configure floating IP
  - ip addr add ${floating_ip}/32 dev eth0
  - echo "ip addr add ${floating_ip}/32 dev eth0" >> /etc/rc.local
  - chmod +x /etc/rc.local
  # Mount database volume
  - if ! blkid /dev/sdb; then mkfs.ext4 /dev/sdb; fi # Only format if not already formatted
  - mkdir -p /mnt/database
  - mount /dev/sdb /mnt/database
  - echo '/dev/sdb /mnt/database ext4 defaults 0 0' >> /etc/fstab
  - chown -R 1000:1000 /mnt/database # Match container user
