# example-tone-grader.toml
# Context and samples for tone evaluation

[contexts.requestType]
type = "string"
question = "What type of request is this?"
description = "The nature of the user's request (e.g., technical help, general inquiry, complaint)"
example = "technical help"

[contexts.userExpertise]
type = "string"
question = "What is the user's expertise level?"
description = "The user's apparent technical knowledge level"
example = "beginner"

[samples.perfect-concise]
userMessage = "How do I save a file?"
assistantResponse = "Press Ctrl+S (Windows/Linux) or Cmd+S (Mac) to save your file."
score = 3
description = "Perfectly concise while being complete and helpful"

[samples.too-verbose]
userMessage = "What's 2+2?"
assistantResponse = "Well, that's an interesting mathematical question! When we add the number 2 to itself, we perform the operation of addition. In this case, if we take 2 and add another 2, we get 4. This is one of the fundamental arithmetic operations that forms the basis of mathematics."
score = -2
description = "Way too verbose for a simple question"

[samples.too-curt]
userMessage = "I'm having trouble understanding how this function works. Could you help me?"
assistantResponse = "Read the docs."
score = -3
description = "Rudely brief and unhelpful"

[samples.good-balance]
userMessage = "Can you explain what a variable is?"
assistantResponse = "A variable is a container that stores data in your program. You can think of it like a labeled box where you put values that you want to use later."
score = 2
description = "Good balance of brevity and clarity"