# grader-base.toml
# Context variables automatically injected by makeGraderDeckBuilder

[contexts.fullConversation]
type = "array"
assistantQuestion = "What was the full conversation?"
description = "The complete conversation as an array of messages with role and content"
example = "[{\"role\": \"user\", \"content\": \"Can you help me write a Python function to sort a list?\"}, {\"role\": \"assistant\", \"content\": \"Here's a Python function that sorts a list:\\n\\n```python\\ndef sort_list(lst):\\n    return sorted(lst)\\n```\"}]"

[contexts.userMessage]
type = "string"
assistantQuestion = "What was the user's original message?"
description = "The last user message from the conversation (extracted for backward compatibility)"
example = "Can you help me write a Python function to sort a list?"

[contexts.assistantResponse]
type = "string"
assistantQuestion = "What was the assistant's response?"
description = "The last assistant message from the conversation (extracted for backward compatibility)"
example = "Here's a Python function that sorts a list:\n\n```python\ndef sort_list(lst):\n    return sorted(lst)\n```"

[contexts.outputFormat]
type = "string"
assistantQuestion = "What format would you like for the output?"
description = "The desired output format for the evaluation"
example = "{\n  \"score\": \"<number from -3 to 3>\",\n  \"reason\": \"<brief explanation of your scoring>\"\n}"