# grader-base.toml
# Context variables automatically injected by makeGraderDeckBuilder

[contexts.userMessage]
type = "string"
question = "What was the user's original message?"
description = "The original message from the user that prompted the assistant's response"
example = "Can you help me write a Python function to sort a list?"

[contexts.assistantResponse]
type = "string"
question = "What was the assistant's response?"
description = "The AI assistant's response to be evaluated against the grading criteria"
example = "Here's a Python function that sorts a list:\n\n```python\ndef sort_list(lst):\n    return sorted(lst)\n```"

[contexts.outputFormat]
type = "string"
question = "What format would you like for the output?"
description = "The desired output format for the evaluation"
example = "{\n  \"score\": \"<number from -3 to 3>\",\n  \"notes\": \"<brief explanation of your scoring>\"\n}"