# line-item-json-grader.toml

[samples.valid_json_extraction]
score = 3

[[samples.valid_json_extraction.messages]]
role = "user"
content = "Extract line items from this invoice text: APPLES 5 LB $10.00"

[[samples.valid_json_extraction.messages]]
role = "assistant"
content = """
{
  "line_items": [
    {
      "description": "APPLES",
      "quantity": 5,
      "unit": "LB", 
      "price": 10.00
    }
  ]
}
"""

[samples.no_json_present]
score = -3

[[samples.no_json_present.messages]]
role = "user"
content = "Extract line items from this invoice text: BANANAS 2 CS $8.00"

[[samples.no_json_present.messages]]
role = "assistant"
content = "I can see the invoice contains bananas, 2 cases for $8.00 total."

[samples.json_with_extra_text]
score = 3

[[samples.json_with_extra_text.messages]]
role = "user"
content = "Extract line items from this invoice text: LETTUCE 4 HD $12.00"

[[samples.json_with_extra_text.messages]]
role = "assistant"
content = """
I've analyzed the invoice and found the following line items:

{
  "line_items": [
    {
      "description": "LETTUCE", 
      "quantity": 4,
      "unit": "HD",
      "price": 12.00
    }
  ]
}

The extraction is complete and ready for processing.
"""