name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

# Limit concurrent runs per issue/PR
# This ensures only one run per issue/PR at a time
concurrency:
  group: claude-${{ github.event.issue.number || github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    defaults:
      run:
        shell: nix develop . --impure --profile /tmp/nix-shell-cache/profile --command bash -e {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: DeterminateSystems/nix-installer-action@main
        with: { determinate: true }

      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Cache nix development shell
        id: nix-shell-cache
        uses: actions/cache@v3
        with:
          path: /tmp/nix-shell-cache
          key: ${{ runner.os }}-nix-shell-${{ hashFiles('flake.nix', 'flake.lock') }}

      - name: Pre-build nix development shell
        if: steps.nix-shell-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/nix-shell-cache
          nix develop . --impure --profile /tmp/nix-shell-cache/profile

      - name: Add dev-shell to PATH
        run: echo "/tmp/nix-shell-cache/profile/bin" >> $GITHUB_PATH

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          timeout_minutes: "60"
          allowed_tools: |
            Bash(bff pr-comments:*)
            Bash(sl help:*)
            Bash(sl log:*)
            Bash(bff commit:*)
            Bash(sl diff:*)
            Bash(sl commit:*)
            Bash(sl pull:*)
            Bash(deno fmt:*)
            Bash(deno lint:*)
            Bash(bff merge:*)
            Bash(bff pr-details:*)
            Bash(sl status:*)
            Bash(sl diff:*)
            Bash(bff ci-status:*)
            Bash(bff format:*)
            Bash(grep:*)
            Bash(bff check:*)
            Bash(bff pr-details:*)
            Bash(bff merge:*)
            Bash(sl status:*)
            Bash(sl diff:*)
            Bash(bff genGqlTypes:*)
            Bash(bff build:*)
            Bash(sl add:*)
            Bash(bff test:*)
            Bash(bff lint:*)
            Bash(sl:*)
            Bash(sl pr:*)
            Bash(sl rebase:*)
            Bash(sl smartlog:*)
            Bash(sl shelve:*)
            Bash(deno test:*)
            Bash(find:*)
            Bash(gh pr view:*)
            Bash(gh pr diff:*)
