# .github/workflows/flakehub-publish-rolling.yml
name: CI + FlakeHub

on:
  push: # keeps the automatic path
    branches: [main]
  workflow_dispatch: # <-- this enables the Run-button
    inputs: # (optional) pass parameters at run-time
      ref:
        description: "Branch or tag to build"
        required: false
        default: "main"
      include_outputs:
        description: "Upload realised store paths?"
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}

      - uses: DeterminateSystems/nix-installer-action@main
        with: { determinate: true }

      - uses: DeterminateSystems/flakehub-cache-action@main

      # build whatever you want cached
      - run: nix develop .#devShells.x86_64-linux.default -c true

      # List and verify sizes before pushing
      - name: List largest files before push
        run: |
          du -sh .
          echo "Largest files:"
          find . -type f -not -path "*/.git/*" -not -path "*/.sl/*" -size +5M | xargs du -sh | sort -rh | head -10
          echo "Checking .flakeignore exists:"
          cat .flakeignore

      - uses: DeterminateSystems/flakehub-push@v2
        with:
          rolling: true
          visibility: public
          include-output-paths: ${{ github.event.inputs.include_outputs }}
          flake-path: "."
          github-token: ${{ github.token }}
