name: Nix Flake actions

on:
  pull_request:
  push:

jobs:
  install-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build server and client
        run: |
          nix build .#deploy -L
          echo "$RUNNER_WORKSPACE/result/bin" >> $GITHUB_PATH
          
      - name: Add environment vars
        run: |
          export BF_PATH=$RUNNER_WORKSPACE
          export BF_INFRA_BIN_PATH=$BF_PATH/infra/bin
          
          echo "BF_PATH=$BF_PATH" >> $GITHUB_ENV
          echo "BF_INFRA_BIN_PATH=$BF_INFRA_BIN_PATH" >> $GITHUB_ENV

          echo $BF_PATH >> $GITHUB_PATH
          echo $BF_INFRA_BIN_PATH >> $GITHUB_PATH
          
          
      - name: Check env vars
        run: |
          echo $BF_PATH
          echo $PATH
          echo $RUNNER_WORKSPACE
          env
          
      - name: Run CI
        run: |
          echo $PATH
          echo $GITHUB_PATH
          
          ./result/bin/direnv allow .
          eval "$(./result/bin/direnv export bash)"
          which bff
          which direnv
          bff ci