name: Publish Dev Version

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Dev Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: npm ci

      - name: Generate short git hash
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update version
        run: |
          cd packages/bolt-foundry/npm
          npm version 0.0.0-dev.${{ env.sha_short }} --no-git-tag-version

      - name: Build package
        run: |
          cd packages/bolt-foundry
          deno run -A bin/dnt.ts

      - name: Publish to npm
        run: |
          cd packages/bolt-foundry/npm
          npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR
        run: |
          cd packages/bolt-foundry
          deno publish --allow-dirty --token ${{ secrets.JSR_TOKEN }}
        env:
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
