name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 1.0.0)"
        required: true
        type: string
      tag:
        description: "NPM tag (e.g., latest, beta, next)"
        required: true
        default: "latest"
        type: string

jobs:
  build-and-publish:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: npm ci

      - name: Update version
        run: |
          cd packages/bolt-foundry/npm
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Build package
        run: |
          cd packages/bolt-foundry
          deno run -A bin/dnt.ts

      - name: Publish to npm
        run: |
          cd packages/bolt-foundry/npm
          npm publish --access public --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to JSR
        run: |
          cd packages/bolt-foundry
          deno publish --allow-dirty --token ${{ secrets.JSR_TOKEN }}
        env:
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}

      - name: Create Git Tag
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a v${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}
