/* @generated */
// deno-lint-ignore-file
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../graphqlContext.ts"
import type { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  BfNode: {};
  CurrentViewer: {};
  CurrentViewerLoggedIn: {};
  CurrentViewerLoggedOut: {};
  JoinWaitlistPayload: { // root type
    message?: string | null; // String
    success: boolean; // Boolean!
  }
  Mutation: {};
  Query: {};
  TestType: { // root type
    count?: number | null; // Int
    id: string; // ID!
    isActive?: boolean | null; // Boolean
    name?: string | null; // String
  }
  Waitlist: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  BfNode: { // field return type
    id: string | null; // ID
  }
  CurrentViewer: { // field return type
    currentViewer: NexusGenRootTypes['CurrentViewer'] | null; // CurrentViewer
    id: string | null; // ID
    orgBfOid: string | null; // String
    personBfGid: string | null; // String
  }
  CurrentViewerLoggedIn: { // field return type
    currentViewer: NexusGenRootTypes['CurrentViewer'] | null; // CurrentViewer
    id: string | null; // ID
    orgBfOid: string | null; // String
    personBfGid: string | null; // String
  }
  CurrentViewerLoggedOut: { // field return type
    currentViewer: NexusGenRootTypes['CurrentViewer'] | null; // CurrentViewer
    id: string | null; // ID
    orgBfOid: string | null; // String
    personBfGid: string | null; // String
  }
  JoinWaitlistPayload: { // field return type
    message: string | null; // String
    success: boolean; // Boolean!
  }
  Mutation: { // field return type
    joinWaitlist: NexusGenRootTypes['JoinWaitlistPayload'] | null; // JoinWaitlistPayload
    loginWithGoogle: NexusGenRootTypes['CurrentViewer'] | null; // CurrentViewer
  }
  Query: { // field return type
    currentViewer: NexusGenRootTypes['CurrentViewer'] | null; // CurrentViewer
  }
  TestType: { // field return type
    count: number | null; // Int
    id: string; // ID!
    isActive: boolean | null; // Boolean
    name: string | null; // String
  }
  Waitlist: { // field return type
    id: string | null; // ID
  }
}

export interface NexusGenFieldTypeNames {
  BfNode: { // field return type name
    id: 'ID'
  }
  CurrentViewer: { // field return type name
    currentViewer: 'CurrentViewer'
    id: 'ID'
    orgBfOid: 'String'
    personBfGid: 'String'
  }
  CurrentViewerLoggedIn: { // field return type name
    currentViewer: 'CurrentViewer'
    id: 'ID'
    orgBfOid: 'String'
    personBfGid: 'String'
  }
  CurrentViewerLoggedOut: { // field return type name
    currentViewer: 'CurrentViewer'
    id: 'ID'
    orgBfOid: 'String'
    personBfGid: 'String'
  }
  JoinWaitlistPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  Mutation: { // field return type name
    joinWaitlist: 'JoinWaitlistPayload'
    loginWithGoogle: 'CurrentViewer'
  }
  Query: { // field return type name
    currentViewer: 'CurrentViewer'
  }
  TestType: { // field return type name
    count: 'Int'
    id: 'ID'
    isActive: 'Boolean'
    name: 'String'
  }
  Waitlist: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    joinWaitlist: { // args
      company: string; // String!
      email: string; // String!
      name: string; // String!
    }
    loginWithGoogle: { // args
      idToken: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}