/* @generated */
// deno-lint-ignore-file
/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../graphqlContext.ts"
import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSON";
    bfGid<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "BfGID";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSON";
    bfGid<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "BfGID";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName> & { count?: connectionPluginCore.ConnectionFieldResolver<TypeName, FieldName, "count"> }
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  BfGID: any
  JSON: any
}

export interface NexusGenObjects {
  BfEdge: { // root type
    id: NexusGenScalars['BfGID']; // BfGID!
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  BfEdgeBase: { // root type
    id: string; // ID!
  }
  BfOrganization: { // root type
    name: string; // String!
    person: NexusGenRootTypes['BfPerson'][]; // [BfPerson!]!
    settings: NexusGenScalars['JSON']; // JSON!
  }
  BfPerson: { // root type
    email: string; // String!
    name: string; // String!
    person: NexusGenRootTypes['BfPerson'][]; // [BfPerson!]!
    settings: NexusGenScalars['JSON']; // JSON!
  }
  CurrentViewer: { // root type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  CurrentViewerLoggedIn: { // root type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  CurrentViewerLoggedOut: { // root type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  JoinWaitlistPayload: { // root type
    message: string; // String!
    success: boolean; // Boolean!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
  BfNode: core.Discriminate<'BfOrganization', 'optional'> | core.Discriminate<'BfPerson', 'optional'>;
  BfNodeBase: core.Discriminate<'BfEdge', 'optional'> | core.Discriminate<'CurrentViewer', 'optional'> | core.Discriminate<'CurrentViewerLoggedIn', 'optional'> | core.Discriminate<'CurrentViewerLoggedOut', 'optional'>;
  GraphQLObjectBase: core.Discriminate<'BfEdgeBase', 'optional'>;
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  BfEdge: { // field return type
    id: NexusGenScalars['BfGID']; // BfGID!
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  BfEdgeBase: { // field return type
    id: string; // ID!
  }
  BfOrganization: { // field return type
    name: string; // String!
    person: NexusGenRootTypes['BfPerson'][]; // [BfPerson!]!
    settings: NexusGenScalars['JSON']; // JSON!
  }
  BfPerson: { // field return type
    email: string; // String!
    name: string; // String!
    person: NexusGenRootTypes['BfPerson'][]; // [BfPerson!]!
    settings: NexusGenScalars['JSON']; // JSON!
  }
  CurrentViewer: { // field return type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  CurrentViewerLoggedIn: { // field return type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  CurrentViewerLoggedOut: { // field return type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  JoinWaitlistPayload: { // field return type
    message: string; // String!
    success: boolean; // Boolean!
  }
  Mutation: { // field return type
    joinWaitlist: NexusGenRootTypes['JoinWaitlistPayload'] | null; // JoinWaitlistPayload
    updateBfOrganization: boolean | null; // Boolean
    updateBfPerson: boolean | null; // Boolean
  }
  Query: { // field return type
    me: NexusGenRootTypes['CurrentViewer']; // CurrentViewer!
  }
  BfNode: { // field return type
    name: string; // String!
    person: NexusGenRootTypes['BfPerson'][]; // [BfPerson!]!
    settings: NexusGenScalars['JSON']; // JSON!
  }
  BfNodeBase: { // field return type
    isLoggedIn: boolean; // Boolean!
    organization: NexusGenRootTypes['BfOrganization']; // BfOrganization!
    person: NexusGenRootTypes['BfPerson']; // BfPerson!
  }
  GraphQLObjectBase: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  BfEdge: { // field return type name
    id: 'BfGID'
    isLoggedIn: 'Boolean'
    organization: 'BfOrganization'
    person: 'BfPerson'
  }
  BfEdgeBase: { // field return type name
    id: 'ID'
  }
  BfOrganization: { // field return type name
    name: 'String'
    person: 'BfPerson'
    settings: 'JSON'
  }
  BfPerson: { // field return type name
    email: 'String'
    name: 'String'
    person: 'BfPerson'
    settings: 'JSON'
  }
  CurrentViewer: { // field return type name
    isLoggedIn: 'Boolean'
    organization: 'BfOrganization'
    person: 'BfPerson'
  }
  CurrentViewerLoggedIn: { // field return type name
    isLoggedIn: 'Boolean'
    organization: 'BfOrganization'
    person: 'BfPerson'
  }
  CurrentViewerLoggedOut: { // field return type name
    isLoggedIn: 'Boolean'
    organization: 'BfOrganization'
    person: 'BfPerson'
  }
  JoinWaitlistPayload: { // field return type name
    message: 'String'
    success: 'Boolean'
  }
  Mutation: { // field return type name
    joinWaitlist: 'JoinWaitlistPayload'
    updateBfOrganization: 'Boolean'
    updateBfPerson: 'Boolean'
  }
  Query: { // field return type name
    me: 'CurrentViewer'
  }
  BfNode: { // field return type name
    name: 'String'
    person: 'BfPerson'
    settings: 'JSON'
  }
  BfNodeBase: { // field return type name
    isLoggedIn: 'Boolean'
    organization: 'BfOrganization'
    person: 'BfPerson'
  }
  GraphQLObjectBase: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    joinWaitlist: { // args
      company: string; // String!
      email: string; // String!
      name: string; // String!
    }
    updateBfOrganization: { // args
      id?: string | null; // ID
      params?: NexusGenScalars['JSON'] | null; // JSON
    }
    updateBfPerson: { // args
      id?: string | null; // ID
      params?: NexusGenScalars['JSON'] | null; // JSON
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  BfNode: "BfOrganization" | "BfPerson"
  BfNodeBase: "BfEdge" | "CurrentViewer" | "CurrentViewerLoggedIn" | "CurrentViewerLoggedOut"
  GraphQLObjectBase: "BfEdgeBase"
}

export interface NexusGenTypeInterfaces {
  BfEdge: "BfNodeBase"
  BfEdgeBase: "GraphQLObjectBase"
  BfOrganization: "BfNode"
  BfPerson: "BfNode"
  CurrentViewer: "BfNodeBase"
  CurrentViewerLoggedIn: "BfNodeBase"
  CurrentViewerLoggedOut: "BfNodeBase"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "BfNode" | "BfNodeBase" | "GraphQLObjectBase";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    __typename: true
    isTypeOf: false
    resolveType: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}