/* @generated */
/* This file is auto-generated by genInterfaceBarrel.ts. */

export * from "apps/bfDb/graphql/GraphQLNode.ts";
export * from "apps/bfDb/graphql/GraphQLObjectBase.ts";
export * from "apps/bfDb/graphql/interfaceUtils.ts";
