[samples.qb-draft-injury]
userMessage = """{
ID: draft-2025-qb-001

Title: Georgia QB Carson Beck Declares for NFL Draft Despite Season-Ending Injury

Content: Georgia quarterback Carson Beck announced Monday he will forgo his remaining eligibility and enter the 2025 NFL Draft, despite suffering a torn ACL in the SEC Championship game that ended his collegiate career. The 6-foot-4 signal-caller threw for 3,485 yards and 28 touchdowns this season while leading the Bulldogs to an 11-1 regular season record. Beck's decision comes after extensive consultation with NFL personnel who still project him as a potential first-round selection despite the injury. Medical evaluations indicate he should be fully recovered by training camp. 'After careful consideration with my family and coaches, I believe this is the right time to pursue my NFL dreams,' Beck said in a statement posted to social media. The Bulldogs will now turn to freshman phenom Gunner Stockton, who performed admirably in relief during the SEC title game.

Published: 2025-01-15T14:30:00Z
}"""
assistantResponse = "Georgia QB Carson Beck declares for 2025 NFL Draft despite torn ACL in SEC Championship game."
score = 1
description = "Good response with specific player name, injury type, and game context. Doesn't match the tone. Very straightlaced, and while accurate, does not reflect the tone of our publication."

[samples.giannis-trade]
userMessage = """{
ID: nba-trade-deadline-004

Title: Nets-Bucks Trade Talks Fall Through; Giannis Stays Put in Milwaukee

Content: The Brooklyn Nets' ambitious pursuit of two-time MVP Giannis Antetokounmpo has officially ended without a deal, according to sources close to both organizations. Negotiations that began early last week broke down Sunday evening when the Milwaukee Bucks' asking price proved insurmountable. The Nets had assembled an aggressive package including Mikal Bridges, Cameron Johnson, four first-round picks, and three pick swaps, but Milwaukee insisted on including guard Cam Thomas in any potential deal. 'At the end of the day, we believe in this roster and Giannis is the cornerstone of our championship aspirations,' Bucks GM Jon Horst said in a brief statement. The Greek Freak, who has two years remaining on his contract, averaged 31.5 points, 11.3 rebounds, and 6.4 assists this season. With the trade deadline now passed, both teams will pivot to their current rosters for the playoff push.

Published: 2025-02-08T22:15:00Z
}"""
assistantResponse = "Nets' trade pursuit of Giannis Antetokounmpo falls through; two-time MVP remains with Bucks."
score = 3
description = "Clear trade outcome with player accolades and both teams identified. Tone is straightlaced, but information dense."

[samples.nfl-draft-contracts]
userMessage = """{
ID: nfl-draft-contracts-2025

Title: Travis Hunter Among Five First-Round Picks Still Unsigned as Training Camps Near

Content: Five first-round selections from the 2025 NFL Draft remain without contracts as rookie training camps begin next week, with Colorado's two-way sensation Travis Hunter headlining the unsigned group. Hunter, selected third overall by the Tennessee Titans, is reportedly at an impasse over offset language in his four-year deal projected to be worth $38.5 million fully guaranteed. The other unsigned first-rounders include Bears quarterback Caleb Williams (1st overall), Cardinals offensive tackle Joe Alt (4th), Falcons wide receiver Marvin Harrison Jr. (5th), and Jets edge rusher Laiatu Latu (8th). 'These negotiations always intensify as camp approaches, but we're confident deals will be completed soon,' said an NFL source familiar with the negotiations. The sticking points typically involve payment schedules, workout bonuses, and offset language that would reduce guaranteed money if a player is cut and signs elsewhere. Last year, all first-round picks were signed by the third day of training camp.

Published: 2025-07-20T09:45:00Z
}"""
assistantResponse = "Travis Hunter among five first-round NFL picks still negotiating contracts as training camps approach."
score = -2
description = "Extremely close to the original headline"

[samples.fifa-club-cup-kickoff]
userMessage = """{
ID: fifa-cwc-2025-opener

Title: Messi Scores Twice as Inter Miami Opens FIFA Club World Cup with 3-1 Victory

Content: Lionel Messi delivered a vintage performance Saturday night, scoring twice to lead Inter Miami to a 3-1 victory over Egypt's Al Ahly in the opening match of the expanded 2025 FIFA Club World Cup. The 38-year-old Argentine maestro opened the scoring in the 23rd minute with a trademark left-footed curler before adding a penalty in the 67th minute after being fouled in the box. Inter Miami's third goal came from striker Luis Suarez in the 78th minute, while Al Ahly's Mohamed Sherif netted a consolation goal in stoppage time. Playing in front of 65,000 fans at MetLife Stadium in New Jersey, Inter Miami became the first MLS club to win a Club World Cup match in the tournament's new 32-team format. 'This is a historic moment for our club and MLS,' said Inter Miami coach Tata Martino. 'But we're not satisfied with just participating - we want to show the world that MLS can compete with anyone.' Inter Miami next faces Bayern Munich on Tuesday in what promises to be a blockbuster group stage encounter.

Published: 2025-06-15T23:00:00Z
}"""
assistantResponse = "Messi scores twice as Inter Miami defeats Al Ahly 3-1 in FIFA Club World Cup opener."
score = -3
description = "Very close to original headline, doesn't add any value or tone."

[samples.nba-finals-update]
userMessage = """{
ID: nba-finals-g2-2025

Title: Thunder Set Finals Record with 22 Three-Pointers in 132-114 Game 2 Victory Over Pacers

Content: The Oklahoma City Thunder put on a historic shooting display Sunday night at Paycom Center, draining a Finals-record 22 three-pointers en route to a dominant 132-114 victory over the Indiana Pacers in Game 2 of the NBA Finals. The Thunder now lead the series 2-0 and are two wins away from their first championship since relocating from Seattle. Shai Gilgeous-Alexander led the barrage with 38 points on 7-of-11 from beyond the arc, while Chet Holmgren added 24 points and 12 rebounds. The Thunder shot an incredible 22-of-38 (57.9%) from three-point range, breaking the previous Finals record of 20 set by the Cleveland Cavaliers in 2017. Indiana's struggles were epitomized by their All-Star backcourt of Tyrese Haliburton and Buddy Hield, who combined for just 28 points on 11-of-34 shooting. 'They were unconscious from three tonight,' said Pacers coach Rick Carlisle. 'We tried different coverages, but they had an answer for everything.' The series shifts to Indianapolis for Games 3 and 4, with the Pacers desperately needing to defend their home court to avoid a 3-0 deficit.

Published: 2025-06-08T23:30:00Z
}"""
assistantResponse = "Thunder set NBA Finals record with 22 three-pointers in 132-114 Game 2 win over Pacers."
score = -3
description = "Nearly verbatim headline."

[samples.penix-sophomore-questions]
userMessage = """{
ID: nfl-qb-year2-analysis

Title: What do we really know about Michael Penix Jr.? Answering one big question for seven QBs entering Year 2

Content: As Michael Penix Jr. enters his second NFL season, questions remain about his development trajectory. After just three starts in his rookie campaign, Penix showed flashes of the arm talent that made him a first-round pick, but also displayed concerning tendencies. His aggressive downfield approach often led to forcing throws into tight coverage, and his habit of locking onto his primary receiver resulted in missed opportunities elsewhere on the field. While Penix has 'all the tools,' analysts note he needs 'some sharpening' - particularly in processing full-field reads and keeping the offense on schedule. The limited sample size makes it difficult to draw definitive conclusions about his career arc.

Published: 2025-06-10T11:00:00Z
}"""
assistantResponse = "Michael Penix Jr. shows promise but needs work on reads and decision-making entering Year 2."
score = -3
description = "Overly vague response lacking detail, don't know the sport, very unhelpful generally."

[samples.watt-contract-holdout]
userMessage = """{
ID: steelers-watt-minicamp-2025

Title: Watt, seeking new deal, skips Steelers minicamp

Content: Pittsburgh Steelers star pass rusher T.J. Watt is not attending the team's mandatory minicamp this week as he seeks a new contract extension. The 2021 NFL Defensive Player of the Year, who has 108 career sacks, is in the final year of his current deal that averages $28 million annually. With Myles Garrett recently resetting the pass rusher market at $40 million per year, Watt's absence signals his desire for a comparable deal. If he misses all three days of minicamp, he faces nearly $105,000 in fines. The Steelers remain optimistic about reaching an agreement, with GM Omar Khan expressing hope that Watt 'will finish his career as a Steeler.'

Published: 2025-06-11T14:30:00Z
}"""
assistantResponse = "T.J. Watt wants more money from Steelers."
score = -1
description = "The tone is great, but it doesn't have enough detail. The story is he skipped camp because of a contract dispute, and that's the missing detail. We could still send it, but it wouldn't be quite what we're looking for."

[samples.draft-picks-unsigned]
userMessage = """{
ID: nfl-draft-contracts-tracker

Title: 2025 NFL Draft first-round pick contract tracker: Travis Hunter headlines 5 rookies who still haven't signed

Content: Five first-round picks from the 2025 NFL Draft remain unsigned as training camps approach, with Colorado two-way star Travis Hunter leading the list. Hunter, selected third overall, is reportedly negotiating offset language and guaranteed money in his rookie deal. The other unsigned first-rounders include offensive tackle Joe Alt (5th overall to the Chargers), quarterback Michael Penix Jr. (8th to the Falcons), wide receiver Rome Odunze (9th to the Bears), and edge rusher Dallas Turner (17th to the Vikings). While rookie contracts are largely predetermined by draft slot, negotiations often stall over offset language, payment schedules, and workout bonuses. Teams typically want offset language to protect against paying guaranteed money if a player is cut and signs elsewhere.

Published: 2025-06-12T09:15:00Z
}"""
assistantResponse = "Some draft picks haven't signed yet."
score = -3
description = "Extremely vague response that fails to mention Travis Hunter, the number of unsigned picks, or any contract details, and doesn't make the reader able to contextualize its importance."

[samples.pacers-thunder-finals]
userMessage = """{
ID: nba-finals-game2-analysis

Title: 2025 NBA Finals: Why Tyrese Haliburton's scoring is least of Pacers' problems if they can't slow down Thunder

Content: The Indiana Pacers trail 2-0 in the NBA Finals after another devastating loss to the Oklahoma City Thunder, and while Tyrese Haliburton's offensive struggles have drawn criticism, the team's defensive collapse is the real story. Haliburton managed just 12 points on 4-of-15 shooting in Game 2, but the Pacers' inability to contain the Thunder's historic offensive explosion - including a Finals-record 22 three-pointers - exposed fundamental defensive breakdowns. The Thunder shot 58% from beyond the arc and scored 132 points, systematically exploiting Indiana's drop coverage and slow rotations. Unless the Pacers can find answers on the defensive end, Haliburton's scoring output becomes irrelevant in a series that's quickly slipping away.

Published: 2025-06-08T23:45:00Z
}"""
assistantResponse = "Pacers losing to Thunder in Finals."
score = -3
description = "Generic response that misses the analytical angle about defense vs. offense, Haliburton's role, and specific game details. No interesting tone, etc."

[samples.pacers-thunder-finals-good]
userMessage = """{
ID: nba-finals-game2-analysis

Title: 2025 NBA Finals: Why Tyrese Haliburton's scoring is least of Pacers' problems if they can't slow down Thunder

Content: The Indiana Pacers trail 2-0 in the NBA Finals after another devastating loss to the Oklahoma City Thunder, and while Tyrese Haliburton's offensive struggles have drawn criticism, the team's defensive collapse is the real story. Haliburton managed just 12 points on 4-of-15 shooting in Game 2, but the Pacers' inability to contain the Thunder's historic offensive explosion - including a Finals-record 22 three-pointers - exposed fundamental defensive breakdowns. The Thunder shot 58% from beyond the arc and scored 132 points, systematically exploiting Indiana's drop coverage and slow rotations. Unless the Pacers can find answers on the defensive end, Haliburton's scoring output becomes irrelevant in a series that's quickly slipping away.

Published: 2025-06-08T23:45:00Z
}"""
assistantResponse = "It turns out you have to lead for more of the game than just the last .03 seconds to win the finals. Pacers drop the second game to the Thunder. Series tied 1-1."
score = 3
description = "Adds significant detail that informs, while giving a witty tone that makes it fun to read."
