[contexts.teamMember]
type = "string"
question = "What is the team member's name?"
description = "The name of the team member being evaluated"
example = "Alice"

[contexts.workSummary]
type = "string"
question = "What is the work summary being evaluated?"
description = "The AI-generated summary of the team member's work to be graded"
example = "Alice worked on team status tracking. She built the GitHub analysis system which helps the team stay informed about what everyone is working on."

# Sample summaries for different score levels
[samples.excellent-summary]
userMessage = "Generate a summary for Alice's work on team status tracking features"
assistantResponse = "Alice worked on team status tracking. She built the GitHub analysis system which helps the team stay informed about what everyone is working on."
explanation = "Perfect example - focuses on what was built, explains the benefit in plain terms, connects to team value"

[samples.good-summary]
userMessage = "Generate a summary for Bob's authentication work"
assistantResponse = "Bob focused on authentication improvements. He fixed several timeout issues that were affecting users and updated the security flow."
explanation = "Good summary - clear about what was done and why it matters, could be slightly more specific about impact"

[samples.poor-summary]
userMessage = "Generate a summary for Carol's infrastructure work" 
assistantResponse = "Carol has been pioneering our revolutionary approach to next-generation authentication paradigms."
explanation = "Too jargony - uses buzzwords instead of plain language, doesn't explain what was actually built"

[samples.terrible-summary]
userMessage = "Generate a summary for Dave's recent work"
assistantResponse = "Dave submitted 8 PRs this week covering features, bugfixes, and documentation."
explanation = "Mechanical activity counting - focuses on metrics rather than meaning, doesn't explain what was accomplished"

[samples.vague-summary]
userMessage = "Generate a summary for Carol's infrastructure work"
assistantResponse = "Carol worked on infrastructure."
explanation = "Too vague - doesn't explain what was built or why it matters"